### ISSUE TITLE
Allow moving people dock between screens

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#10]
You've probably already thought about this, but here's a feature request.  

On a multi monitor set-up, it would be great to be able switch the bar of little people circles to another screen.  I used to dedicate my entire left monitor to Sqwiggle, and would code on my main monitor.  Now the circles overlap the left part of a few lines of code.  The auto-hide feature helps a lot, but when I'm in a call (which we do semi frequently during pair-programming sessions), the circles are visible and cover code.  

If I could move it to another monitor (I have 3), it would solve my issue.  Other ideas are allowing hiding the circles even during a call, or even simply moving them a different side of the main monitor (I would put it on the bottom right of my main monitor if I couldn't move it to another one).

**Comment by willbarrett** [comment]
Hey - thanks for the feedback! We're working on a preference to move the dock to the other side of the screen currently, and we'll make sure the product folks hear of the other ideas!

**Comment by tommoor** [comment]
The ability to choose which screen is a solid idea to go along with flipping which side.. we definitely want it to be flexible for everyone's preferences :smile:

**Comment by CyborgMaster** [comment]
Awesome.  Thanks for the taking this under consideration.  The other side of the screen wouldn't solve the problem for me unfortunately.  I run a 6 buffer emacs across the whole screen on my main monitor and the other side would simply block another file.  

This is what it looks like currently: 
![screen shot 2015-05-07 at 11 07 00 am](https://cloud.githubusercontent.com/assets/1882579/7521205/4cad6f26-f4a9-11e4-9e3c-303b312af434.png)
(Sorry for the small size, I run a 4k screen.  You can barely see the conversation bubbles on the left).  

Another monitor would be ideal.  
Thanks again!

**Comment by tommoor** [comment]
Wow, quite the setup! Any interest in resizing the heads as they are so small or does this work well for you because you're used to 4k?

**Comment by CyborgMaster** [comment]
The current size is actually perfect for me.  The monitor is 40", so the pixel density is about what you get on a normal screen, there's just a lot of pixels.  They currently end up about 1cm in diameter on my screen.  

Resize might be important as you include video, but that would totally depend on how you work that in.  My normal flow with Sqwiggle was to keep it running full screen on my laptop (15" mbp retina) to the left of my big monitor), that way I was always able to see who on my team was at their desk at a glance and conversation video was always a good 13" diagonal so it felt close to face to face.

**Comment by iwaffles** [comment]
I'd like to give this my :+1: – I hide the OS X dock on the left hand side and this might get in the way when using the dock.

Love the way this looks. I think having a menu bar only option would be nice (drop down and select someone).

**Comment by awsmsrc** [comment]
cheers @iwaffles we're building it as we speak (see what i did there)

**Comment by iwaffles** [comment]
![ship](https://cloud.githubusercontent.com/assets/7333/7591747/6b2baa4c-f884-11e4-88a1-64af9aca52c1.jpg)

**Comment by tommoor** [comment]
:star2: fav :star2:

**Comment by sdhull** [comment]
:+1: I keep my dock on the left and don't want to have to adjust to putting it on the right so this will be awesome!  :smile:

**Comment by tommoor** [comment]
We just released the ability to move the dock to the right in 0.3.0! http://speak.io/changelog#0.3.0

Moving to other screens is also on the list for one of the next couple of releases.

**Comment by CyborgMaster** [comment]
Love it.  I've got a little more room there, so I've moved it to the right for now.  Looking forward to second monitor support.  Then I can leave it always showing instead of having to use auto hide.

**Comment by tommoor** [comment]
Quick update, @awsmsrc has been actively working on this and we expect it to be in the next app release.

**Comment by CyborgMaster** [comment]
Awesome. Will be great to finally be able to leave the people bar visible.

- Jeremy

**Comment by tommoor** [comment]
We just pushed out an update that includes this functionality, thanks for the suggestion!

http://speak.io/changelog/#0.3.3

**Comment by CyborgMaster** [comment]
You're welcome.  Just got back from vacation and tried this out.  I love it! Thanks.
