### ISSUE TITLE
Idle detection doesn't turn Instant Audio back on

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#101]
Per our discussion in #96, I have been trying the idle detection feature for managing getting calls when I am away from my desk.  It seems that I have found a bug.  

I can see the idle detection working.  When I step away from my desk, my status changes to Call & Accept.  However, when I come back, it doesn't change to Instant Audio.

**Comment by tommoor** [comment]
@CyborgMaster you're right, it looks like this has been broken... sorry about that. We'll get it restored for the next release

**Comment by tommoor** [comment]
We've fixed this in todays release, sorry for the trouble: http://speak.io/changelog/#0.4.4

**Comment by CyborgMaster** [comment]
Cool. I'll turn it back on and see how it goes.
