### ISSUE TITLE
Invite doesn't work

### ISSUE THREAD

**Issue by smogil-squadup** [speak/issues#102]
http://recordit.co/8PLAaQkit1

**Comment by tommoor** [comment]
Hey, could you try restarting the app and see if that helps? Thanks!

**Comment by smogil-squadup** [comment]
Still no luck after restarting, screengrab updated: http://recordit.co/yOls95m9iB

**Comment by tommoor** [comment]
@smogil-squadup ouch, we'll take a look at that as a matter of priority. In this case as your team signed up with Slack you can simply have your teammates signin with the same Slack team - no invites are necessary :)

Hope this helps!

**Comment by smogil-squadup** [comment]
Excellent, thanks!

**Comment by tommoor** [comment]
We've fixed this in todays release, sorry for the trouble: http://speak.io/changelog/#0.4.4

**Comment by smogil-squadup** [comment]
Awesome, thanks! Do you know what the issue was exactly?

**Comment by tommoor** [comment]
@smogil-squadup in this case we hadn't accounted for a potential state that the app could get into and were referencing data that didn't exist :frowning:

**Comment by smogil-squadup** [comment]
Got it. Thanks again for the amazing customer service!
