### ISSUE TITLE
New UI / UX Brainstorm

### ISSUE THREAD

**Issue by ericbieller** [speak/issues#105]
Hey all! We've got some new UI we've been working on and **we'd love to know what you think**.

The main advantages are:

- Customizable so you can use Speak the way you want.
- More intuitive UI for handling multiple teams / orgs.
- Solves technical difficulties with current form factor which make a Windows app damn near impossible.
- Allows us to reduce CPU usage through better window management.
- Sets us up for some really interesting functionality in the future.

*Here are the highlights:*

**Multiple view options**
The app view gives you more context and controls, but can be docked to the right with one click (or shortcut key) for a more classic Speak experience.

**Call controls**
The new control box remains on top of other windows during a call, making it super obvious what's going on at a glance. This will morph into our existing video box if video is enabled or if the box is expanded.

**Multiple team support**
Instantly filter between teams via hotkeys.

![app](https://cloud.githubusercontent.com/assets/740552/8436591/3ebbd152-1f0e-11e5-8fb7-ecf981823d54.png)

**Comment by JohnONolan** [comment]
This is looking just fantastic. I love the teamswitching familiarity of Slack - that will be instantly intuitive.

One question comes to mind from the slightly awkward icons in the left window.

**Do the + and search icons need to be there?** How regularly will they be used? For us, adding team-members was a one-off thing. After that, we only add new team members once every couple of months. Does a UI element deserve that much priority if it won't be used very often? Similarly, if I only have 5 users I'm never (ever) going to use search.

Suggestion: 
* 4 or fewer team members: Show + icon
* 5-9 team members: No icons (yay)
* 10 or more team members: Show search icon

(I assume that either way, search and + will be available in the default system menu dropdowns anyway)

**Comment by tommoor** [comment]
Hey @JohnONolan - awesome feedback! We're envisaging that the "+" icon will be used for a couple of things similar to how it is in github, adding coworkers definitely, also creating meetings / scheduled calls down the line

![image](https://cloud.githubusercontent.com/assets/380914/8577031/dbbb1812-255a-11e5-83a6-f9560e4cf9cb.png)

I totally get what you mean and we should definitely hide the search icon when the team is small at the very least, that's something i'll make sure to get implemented :smile:

**Comment by JohnONolan** [comment]
Oh wow that's cool :grin: makes a ton of sense!

**Comment by mull** [comment]
Just dropping in to say that's some darn nice looking stuff folks! ;)

**Comment by ericbieller** [comment]
Hey all, just wanted to post a quick update. Most of the new version is implemented and we're doing a ton of work on the backend to make Speak more reliable, quicker and higher quality. 

Multiple team support is one of our most requested features, and I'm happy to say it's working really well! You can choose to see everyone, or filter by team with a couple clicks or via a shortcut key. This will also enable calls across your various teams.

![image](https://cloud.githubusercontent.com/assets/740552/8729977/13fd2b68-2ba3-11e5-80ff-67f302fd5413.png)

We're also trying to keep inviting easy and intuitive:

![image](https://cloud.githubusercontent.com/assets/740552/8729997/310c42fc-2ba3-11e5-81e0-1bcbf2b7b788.png)

We've refined the dock to make it more compact and functional:

![image](https://cloud.githubusercontent.com/assets/740552/8730046/7dccebc8-2ba3-11e5-9e54-03923a867c48.png)

Our goal is to make Speak feel super light and friendly, so we've re-worked on the call box to make it a bit more compact and unobtrusive:

![image](https://cloud.githubusercontent.com/assets/740552/8730076/a29ff74c-2ba3-11e5-9356-9956245715dd.png)

That's it for now. We really appreciate the comments so far. Let us know if you have any other ideas or feedback on the new direction!

**Comment by tommoor** [comment]
aaaaannddd... this is all out of the door today in v0.5.1! Thanks to those that provided feedback, of course we'll keep iterating, many improvements to come
