### ISSUE TITLE
Trigger Missed Call Notification Sooner

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#106]
Now that idle reset works again (thanks for #101), I've been using it and it works great.  The missed call feature works well too, however I would like to change the way it works.  Right now I only get the red circle with a number in it when they caller waits until the call times out (~10 rings).  If they give up after 2 rings for example, then I don't get a missed call notification.  

I would like it to work how my cell phone does.  No matter how long they let it ring I get a notification (even if it is only like half a ring).  Right now my co-workers have to endure ~30 seconds of the ringing noise to make sure I know they called.  

I could also see an argument for an configurable setting for how long a person has to let it ring before it leaves a notification, but I think that no delay is a much more useful default than waiting for a full timeout.

What do you think?

**Comment by tommoor** [comment]
@CyborgMaster I definitely see your point. So in summary if someone calls, lets it ring for a few seconds and then cancels the call this should leave a missed call notif?

**Comment by CyborgMaster** [comment]
Definitely.

- Jeremy

**Comment by tommoor** [comment]
I'm happy to go with the crowd on this one - @ericbieller @awsmsrc @willbarrett - any thoughts?

**Comment by awsmsrc** [comment]
I've thought the same a thing a few times to be honest.
+1

**Comment by willbarrett** [comment]
I'm happy to go this direction.

**Comment by ericbieller** [comment]
+1, good idea

**Comment by CyborgMaster** [comment]
Looks like this was finished a little while ago.  Any guess as to when it might end up in an update?  We would love to use it.

**Comment by tommoor** [comment]
We're aiming for Wednesday for the next release 😀

**Comment by CyborgMaster** [comment]
Awesome!  We'll look for it.
