### ISSUE TITLE
0.4.5 update won't install in /Applications

### ISSUE THREAD

**Issue by zestyping** [speak/issues#108]
Hi!  I have Speak 0.4.4 (16).  I can't log in because there's a red box that says "Just a second, your client is out of date" in the login window.  The login window offers no obvious way to correct this, nor instructions for how to do so.

Clicking the menu bar icon shows a menu with a Check For Update option.  When I select that option, the option changes to Downloading Update.  A few minutes later a "Speak Update Available" prompt pops up.  I click Install.  Speak closes and reopens.  Nothing appears to have changed: About Speak still reports "0.4.4 (16)" and I still get the red error message preventing me from logging in.

**Comment by tommoor** [comment]
Hey @zestyping - the update should happen automatically. It could be that the app is stored in a place where it doesn't have permissions to write the update? We have a known issue where if administrator permissions are needed then it won't be able to update right now...

The best solution might be to either close and move the app or download fresh from the speak.io homepage

**Comment by zestyping** [comment]
Thanks!   That's exactly the case, yes—Speak is installed in /Applications.  I have deleted and redownloaded Speak and it's working now.

Doesn't /Applications require administrator permissions on all Macs?

**Comment by tommoor** [comment]
@zestyping it usually doesn't by default. I'm going to close this issue now you're sorted as we are tracking the admin permissions issue elsewhere :smile: 

Thanks for using Speak!
