### ISSUE TITLE
Check for updates before logging in

### ISSUE THREAD

**Issue by mull** [speak/issues#109]
When I got the last update I was logged out (either for a reason or without one), but I couldn't log back in because my client was out of date. I could go through the slack login process, but got denied because of the version mismatch (my version was 0.4.4 I think, `current_newest - 1`. :)

If I clicked on "Check for updates" manually in the menu bar and let it update everything worked afterwards.

**Comment by awsmsrc** [comment]
hey @mull hows it going?

This was entirely intentional as there were breaking changes in the backend.
This doesn't happen for every release.

Hope that helps!

**Comment by mull** [comment]
Hey @awsmsrc ! Life's good here in Berlin. How are you? :)

I get that it was intentional. However all 4 of us got stuck on the login screen saying something like "Your client is out of date. Please wait." or something like that. Sure, except the client wasn't actually updating itself. Not until I figured out I had to do it manually could we all log in. Hope that helps!

**Comment by tommoor** [comment]
It *should* have updated itself so there must be some sort of bug here. I also think that this UI could be much improved with a friendly screen whilst the app auto-updates, reopening.

**Comment by tommoor** [comment]
- [ ] catch the error that app is out of date
- [ ] start downloading update automatically
- [ ] show the user a holding screen similar to connecting perhaps? /cc @ericbieller 
- [ ] automatically restart when the update is ready.

**Comment by ericbieller** [comment]
User flow:

- Updates in background -> once complete, user sees banner "There's a new version of Speak! [Install]"

- User logs in (or sleep / wake) -> forced update found -> user sees update screen w/ progress, can't access anything else -> update completes -> app relaunches -> show banner with link to changelog?

**Comment by tommoor** [comment]
Glad to say that all of these improvements are now in place :smile: - Hopefully we won't need to force an update like this very often but next time it will be a delightful experience instead of a terrible one! :tada:
