### ISSUE TITLE
One-click Conversation

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#11]
One of my favorite features in Sqwiggle is the one-click conversation.  Currently Speak requires two: once on the bubble and once on "Instant audio."  I assume the pop-up is there because you plan to add more options (maybe choose between video and audio-only).  I would prefer to have a left click on the bubble start the default conversation (audio+video when its available), and have right-click open the menu.

**Comment by tommoor** [comment]
Just discussed, we agree and we're going to change this. :clap:

**Comment by CyborgMaster** [comment]
Cool.  Looking forward to it.

**Comment by tommoor** [comment]
@CyborgMaster we just released a new version, 0.2.8 which includes alt-click on a user to skip the menu

**Comment by CyborgMaster** [comment]
We just downloaded it and tried it.  Works great.  @tommoor have you considered have the normal click start the conversation and the alt-click open the menu.

**Comment by tommoor** [comment]
I implemented it internally and it felt weird that sometimes it would trigger a direct call, and in other situations we open a menu (ie, on your own user or when already in a call). 

The menu is about to become a lot more useful so we're going to see how it feels over the next week few weeks as items get added - not written it off yet, but it didn't feel quite right either...

**Comment by CyborgMaster** [comment]
That makes a lot of sense.  Just thinking back to the Sqwiggle interface, what happened when you clicked on yourself in Sqwiggle?  That didn't start a conversation, but I seem to remember it still being intuitive.

**Comment by tommoor** [comment]
It updates your snapshot :smile: 

btw, changelog for todays release is here: http://speak.io/changelog#0.2.8

**Comment by CyborgMaster** [comment]
Cool.  Yeah we had already found the idle disable.  That's really good because there isn't as much of a visual indicator that you're in a call as there is in Sqwiggle, so you could get back to your desk and not know someone is listening.

**Comment by tommoor** [comment]
We're counting this as covered by the alt-click for now. Going to try and do a better job of exposing this functionality to folks though :smile:
