### ISSUE TITLE
Video randomly closes

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#110]
It seems like with the new version (4.5) that video chat appears to be broken.  When I start a video call it works for 30 seconds to a minute and then the pop-out window suddenly disappears and my web cam light goes off.  After that happens I am unable to restart video during that call.  

Let me know if you need any other diagnostic information.  Currently video is unusable for me.

**Comment by tommoor** [comment]
@CyborgMaster thanks for the report, looking at this right now!

**Comment by tommoor** [comment]
@CyborgMaster we've tracked down the issue and put a fix in, just going through tests right now.

**Comment by CyborgMaster** [comment]
Wow!  Impressive turn around speed.  Thank you!

**Comment by tommoor** [comment]
Well, this is pretty much the worst bug we can think of :tongue:

**Comment by tommoor** [comment]
Just released a new version 0.4.6 which includes the fix for this issue, thanks for your patience

**Comment by CyborgMaster** [comment]
We just tested it. Works great thanks.
