### ISSUE TITLE
App does not stay signed in

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#111]
Under certain circumstances, the application will require a new sign-in each day. This seems to be related to Slack sign-on.

**Comment by tommoor** [comment]
The slack signon *could* be a read herring as obviously a lot of users do use this method.

**Comment by willbarrett** [comment]
Agreed - anyone with more information on this, please share!

**Comment by tommoor** [comment]
Possibly related to https://github.com/atom/electron/issues/1731 - localStorage not being persisted

**Comment by tommoor** [comment]
We believe this has been fixed in version 0.4.7 today - if anyone on this version or above still sees this issue please leave a comment :smile:
