### ISSUE TITLE
User bubble pop-out menu overflow cut off

### ISSUE THREAD

**Issue by callovarne** [speak/issues#112]
![image](https://cloud.githubusercontent.com/assets/984702/8833707/1b9f5a96-3065-11e5-89da-1647d45616b6.png)

## Steps
1. Enter long status message

### Expected behavior
User bubble pop-out menu content scrolls or embiggens.

### Actual behavior
User bubble pop-out menu content is cut off.

**Comment by willbarrett** [comment]
Thanks @callovarne! We'll get this fixed up.

**Comment by tommoor** [comment]
We've fixed this all up in the new version, in fact we totally lost this menu in favor of a more native feeling OS menu :smile:
