### ISSUE TITLE
Window seizes focus all the time

### ISSUE THREAD

**Issue by benkuhn** [speak/issues#114]
Hi guys, thanks again for making Speak :)

I quite frequently observe Speak throwing up a login window that seizes focus (including dragging me across desktops if I'm on the wrong desktop). I'm not sure what circumstances trigger this exactly, but it's quite annoying, especially when it happens frequently (I'm having some login/client update issues right now and it happened three times while writing this comment). It would be killer if you could replace these with a desktop notification, which is much less intrusive. Thanks so much!

Ben

**Comment by tommoor** [comment]
Hey Ben!

Well, we'd definitely prefer to get to the bottom of the login/update issues as a matter of priority - ideally it should be okay if login seizes focus as this should happen at most once every couple of months :smile: 

Do you have any more details on the update issues at all?

**Comment by benkuhn** [comment]
Turns out they were actually just UX weirdness, not actual login/update issues. (Sorry to worry you!)

- I got an error message that was something like "you need to update your client, please wait a bit" so I thought it was already auto-updating. So the next time it seized focus on me, I thought it was done auto-updating and tried to log in again (and got the same error). This happened a couple times.

- I also got a Slack "you've run into a glitch!" page while trying to log in once, possibly due to me double-clicking a Slack button (either way probably not Speak's fault).

- Then I tried selecting "check for updates" from the update menu and it actually started downloading the update, so next time it seized focus, I thought it had finished downloading and tried to log in again, but still got the update.

Once I had correctly waited for the update to finish and install, everything worked as expected.

I'm not 100% sure I recall the sequence of events correctly since I was distracted by other stuff. Also I'm not sure what triggered Speak to seize focus there, so it's possible that I took other actions in the middle that I don't remember. But anyway I hope it's at least somewhat helpful.

**Comment by tommoor** [comment]
Hey Ben, we've fixed this all up in the new version - thanks! :smile:
