### ISSUE TITLE
Bring back the menu bar icon!

### ISSUE THREAD

**Issue by laserlemon** [speak/issues#115]
I, like many people, am a dock minimalist. My threshold for introducing a new app into my dock is _much_ higher than my menu bar threshold. I'd love to at least have the option, which I think is pretty common across many apps.

**Comment by truppert** [comment]
+1 on this request ^

**Comment by tommoor** [comment]
Hey! We brought in a dock icon as we now have the traditional floating window view and it definitely seemed strange to have that without a dock icon. How about an option to hide the dock icon when Speak itself is docked, would that do the trick?

**Comment by laserlemon** [comment]
![That's a good idea](http://media.giphy.com/media/FmijXcVr53g2I/giphy.gif)

**Comment by cwhenderson20** [comment]
+1 on this!

**Comment by respectTheCode** [comment]
+1

**Comment by anup-ap** [comment]
Hiding the OSX Dock is a good first step but not entirely the same as bringing back the menubar icon which the OP requests.  +1 vote from me.  I do like having the ability to now bring the app to the foreground via Cmd-Tab.

**Comment by joshuaoliver** [comment]
+1 to this.

**Comment by ersatzryan** [comment]
Definitely should be a preference for menubar vs dock

**Comment by ryanjcollier** [comment]
+1

**Comment by tommoor** [comment]
Hey everyone! Happy to let you know that we've added this option in todays release (0.5.3) under 'appearance' in preferences:

![image](https://cloud.githubusercontent.com/assets/380914/9360812/1df82958-465e-11e5-9ebf-934eb70acd97.png)

The app will auto update next time you connect or hit the "check for updates" option in the application menu!

**Comment by laserlemon** [comment]
:tada: :clap: :trophy: :bouquet:

**Comment by laserlemon** [comment]
Thanks for bringing this back, but I regret to inform you that it doesn't exactly work as it should yet.

When I select the new "Only in Menu Bar" option, my dock icon does indeed disappear and the icon appears in the menu bar. But clicking the menu bar icon doesn't give me any dialog, nor does it focus the app.

Then when I quit the application and restart it (which I had to do through Activity Monitor), the old "Only in Dock" option is selected again and the icon does indeed appear in the dock rather than in the menu bar.

So close! Can't wait to get this ironed out! Thanks again!

**Comment by willbarrett** [comment]
Hey @laserlemon - I'm going to open new tickets with improvements for the menu bar icon. We'll get them fixed up!

**Comment by willbarrett** [comment]
broken out into https://github.com/speak/issues/issues/129 and https://github.com/speak/issues/issues/130 - not saving the preference was the result of an unclean application exit, which will be resolved by adding the option to quit.

**Comment by laserlemon** [comment]
Thank you!
