### ISSUE TITLE
Remove someone from team

### ISSUE THREAD

**Issue by danaspiegel** [speak/issues#116]
I'd like to be able to remove someone from a team. Right now, there is no obvious way to click on a person's listing in the contact window and remove them from the team.

**Comment by tommoor** [comment]
Hey Dana! That's definitely something we need to add, will get this in a release very soon. In the meantime if you email howdy@speak.io with the details we can remove those folks for you :)

**Comment by ryanjcollier** [comment]
+1

**Comment by tommoor** [comment]
Happy to let you know this has been added in the latest release today :smile:
