### ISSUE TITLE
Slack /slash command

### ISSUE THREAD

**Issue by ryanjcollier** [speak/issues#118]
We love the fact you can log in using Slack! It would really be useful to start a call using a Slack command such as /call @jon or even start a meeting with everyone that is present in a channel. This would get really "interesting" with scripting.

Also being able to mirror account presence would be nice as well.

**Comment by saenzramiro** [comment]
+1

**Comment by tommoor** [comment]
We're now testing this out, take a look at the instructions here to be a part of the test: 

http://help.speak.io/article/41-slack-integration
