### ISSUE TITLE
Global Shortcuts menu seems off

### ISSUE THREAD

**Issue by drobinson** [speak/issues#120]
Looks like there's another option there, but I can't see it:

https://www.dropbox.com/s/ch74fil236z5agd/Screenshot%202015-08-10%2010.18.25.png?dl=0

**Comment by tommoor** [comment]
Definitely some rendering wonkiness here, there is no additional shortcut option here it's just a rendering glitch!

**Comment by tommoor** [comment]
We've revamped the preferences area in todays release (0.5.3) - I'm sure you'll no longer see this glitch :smile: - thanks for the report!
