### ISSUE TITLE
[Multiple Monitors] Screen Sharing

### ISSUE THREAD

**Issue by drobinson** [speak/issues#121]
By default, it looks like screensharing shows two of my 3 monitors.  FWIW I have two 1920 x 1080 monitors and my built in 13.3-inch (2560 x 1600) running.  Clicking Screen Sharing during a call immediately shows both 1080 monitor displays

**Comment by tommoor** [comment]
Absolutely agree that this is far from ideal behavior :( We're tracking this issue at #72 as it really ties in with choosing which screen you'd like to share.
