### ISSUE TITLE
Turn off Auto Answer by default?

### ISSUE THREAD

**Issue by drobinson** [speak/issues#122]
It's nice that I can set auto answer to turn off automagically while I'm away, but I think most privacy conscious people would like for that to be the default.  I'd much rather have to answer all calls by default, and actively turn on auto-answer.  It should also be made more clear in the dock that auto-answer is currently "on".  My co-workers are apprehensive to keep the application installed because of this behavior.

**Comment by tommoor** [comment]
Thanks for the feedback, you can turn auto answer on/off at any time by clicking on your own face. If the icon shows a full green circle then you're in auto answer, if it's half a circle then it will call so you can choose your preferred level of privacy/speed :smile: 

We could definitely do a better job of messaging this and are working on some improved iconography/onboarding for future versions.
