### ISSUE TITLE
"Couldn't get a connection" message always shows

### ISSUE THREAD

**Issue by megmo** [speak/issues#123]
I've been testing the app with a couple co-workers today and I noticed that whenever I undock my contact list I have a pink banner that says "Whoops, we couldn't get a connection." I didn't have it when I first logged in, but it's hung around for a couple hours—even after I've had several voice and video calls. 

I can X out of the banner to close it, but it comes back a bit later after I've docked/undocked the contact list again.

Screenshot: http://cloud.raven.im/image/3L0a0p2H1a1W

**Comment by tommoor** [comment]
Hey Megan! I believe this would happen if a call failed for some reason :cry: - we'll take a look at the logs on your account and see if anything jumps out, sorry for the annoyance!

**Comment by megmo** [comment]
OK, thanks! I did have trouble answering a call—I clicked the answer button a million times and nothing happened. Not sure if that would count as failed or just unanswered, though.

**Comment by tommoor** [comment]
We have a fix for this in the next update - thanks :smile:
