### ISSUE TITLE
Dock jumps to center of the screen when waking from sleep

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#125]
Replicated on a Macbook Pro. From support chat:

<blockquote>It seems like since no-one is there, I'll just report it here:
As I close the lid of my Macbook, it falls asleep, but when I reopen it, the Speak dock (which is normally of the far left of my screen) floats in the middle. I only resets back to the left when I change the settings of it. A bit inconvenient, as I do this quite often...</blockquote>

**Comment by tommoor** [comment]
#126
