### ISSUE TITLE
Dock appears in middle of screen after login

### ISSUE THREAD

**Issue by kliptonize** [speak/issues#126]
As my dock automatically hides, it reappears when I hover over the left side of my screen. Unfortunately, the lower left corner is used to put my screen to sleep, so right before the screen gets dark, I can see my dock appear again. Not a problem here.
But, whenever I log back in, the dock appears in the middle of my screen (as seen below) until I interact with its visibility (ex: change the dock settings, hover over the left side of my screen..)

<img width="1367" alt="screen shot 2015-08-13 at 14 42 53" src="https://cloud.githubusercontent.com/assets/7501293/9249937/9ce726a4-41c9-11e5-819f-bab1695f3efd.png">

Not a critical issue, since it is easily fixed with the interface, but still a bit annoying..

**Comment by tommoor** [comment]
Thanks for bringing this to our attention, it looks kind of silly just hovering there eh? We'll get this fixed up :smile:

**Comment by kliptonize** [comment]
It does both look silly, and happens when I plug in another screen indeed :)
