### ISSUE TITLE
Can't receive call when making a call

### ISSUE THREAD

**Issue by truppert** [speak/issues#128]
When I call a co-worker, and they call me at the same time, neither of us can answer the call.  We end up having to play tag until one of us can answer.

**Comment by tommoor** [comment]
Hey Taylor, good *call* ... this one's an annoying bug, we're also aware of this one and going to get this fixed up!

**Comment by willbarrett** [comment]
Hey @truppert - we believe we've resolved this in 0.5.3, which was just released.
