### ISSUE TITLE
No way to quit the application when in tray-icon-only mode.

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#129]

**Comment by xavhan** [comment]
+1 for that issue as well

In a lot of applications `alt+click`on the tray-icon open a panel with somme settings. I think that woulb be great to integrate that too :)

**Comment by willbarrett** [comment]
Hey all - we've added an option to quit the app when clicking on your own image, right below 'Sign Out'. Let us know if that doesn't solve all the issues here! This is in 0.5.3, which was released today.
