### ISSUE TITLE
Keyboard shortcut to toggle between Dock and Full modes

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#135]
Seeing as this takes a few clicks in the current version.

**Comment by aeromusek** [comment]
+1! To be honest, that's what I expected would happen when I used the **Toggle the dock** shortcut :smiley:

**Comment by willbarrett** [comment]
You are so right @aeromusek ! I expect we'll have two shortcuts going forward - one to hide and show the dock (which will be the current 'Toggle the dock' shortcut renamed to something better), and a new one that allows switching between docked mode and full mode.

**Comment by tommoor** [comment]
The next release will have the ability to show both the main window and dock at the same time, so this won't be needed.
