### ISSUE TITLE
Eliminate Audio Lag

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#137]
This has started to become a big issue for us.  The longer an audio call lasts, the longer the audio lag gets.  It's been particularly bad lately, but that's most likely randomness.  After about 5 minutes it's a couple seconds behind, and any call longer than that quickly becomes unusable and we have to restart it.  Ending and restarting the call fixes the lag and makes the audio realtime again.  

The problem with restarting the call as a workaround is the idle timeout.  Right now its only about 30 seconds of not touching the keyboard and mouse (which I would like to make much longer btw), and so after even a short call, speak thinks we are both idle.  Then the person who wants to restart the call ends the current call and tries to call the other guy back, but this guy is now idle and the call rings instead of auto-connecting.  This makes this restart process take 5-10 seconds, and if we have to do it every 5 minutes it becomes very untenable, exponentially so if there are multiple people on the call and we are trying to have a meeting.  

It seems to me that this is a buffering problem.  It seems to happen every time the internet, which is quite frequently even on a good connection.  Most of the time, these blips last much less than a second, so the growth is slow, steady, and imperceptible.  However, on the rare occasions when the blip lasts more than half a second (video and audio freeze), then when they come back the audio lag increases by exactly the length of the pause.  This strikes me as a buffering issue because none of this audio is lost, I still hear everything my co-worker said, it just pauses for a bit while the packets are delayed.  They when they all arrive in a rush, they are added to the audio buffer, which then continues to play in realtime, now simply delayed by the length of the pause.  

The way the video handles this currently in speak (I understand the audio and video use different systems), is it plays catchup.  It appears to skip frames as necessary to get back to real time (buffer < .25 seconds I would guess).  The result in speak is that the most obvious indicator that you are having a problem with this issue is that you will see the person talk over video several seconds before you will hear their words.  

Interestingly enough, Sqwiggle handles this just fine.  If the internet blips, you can hear it go into catchup mode where the sound will play ~twice as fast until it gets back to real time.  Please port this functionality to Speak!

Thanks.

**Comment by willbarrett** [comment]
Hey @CyborgMaster - thank you for the report. We're on it!

**Comment by CyborgMaster** [comment]
You're welcome.  We've been dealing with this issue for a while now (it's been there since the beginning), so if you have any questions about patterns, symptoms, etc, I'd be happy to help.

**Comment by willbarrett** [comment]
Awesome - we may have some questions for you as we dig further into it.

**Comment by tommoor** [comment]
Hey guys, just wanted to make you aware that we're making solid progress on this and it appears to be a server side issue - so once we roll out improvements you should see the benefit without the need for another update. 

We'll keep you informed!

**Comment by CyborgMaster** [comment]
Awesome!  I'm excited to try it out when you get the fix pushed.

**Comment by willbarrett** [comment]
Hey @CyborgMaster - we just pushed a fix to our production media servers. Give it another try and let us know whether you see the audio lag again? If it doesn't repro in the next 24 hours, I'll go ahead and close this ticket.

**Comment by CyborgMaster** [comment]
We are testing it today.  So far, so good. Thanks!  I'll write back at the end of the day and give you any updates.

**Comment by willbarrett** [comment]
Hey @CyborgMaster - everything still good here?

**Comment by CyborgMaster** [comment]
We didn't see any lag yesterday. Things are looking good!

- Jeremy

**Comment by willbarrett** [comment]
Awesome! Closing this as resolved.
