### ISSUE TITLE
Conversation window should pop-up on same screen main speak window/dock is on

### ISSUE THREAD

**Issue by RalphMickelson** [speak/issues#138]
I work on a multi-monitor setup. My laptop (which, of course, has the camera) is where I run my Speak window/dock. It is not my main monitor, however.

At the start of each conversation, I have to drag the video window over to the laptop, so that when I look at the video window, it appears to the camera that I am looking at the other person.

Would be nice if the conversation/video window would pop-up on the screen that the main speak window uses.

**Comment by tommoor** [comment]
Sounds like a reasonable request that could be easily fixed - I'll see what we can do :smile:

**Comment by CyborgMaster** [comment]
Another way this could be solved is to have the window open in the same place it was the last time it closed.  That the positioning could be fine tuned.

**Comment by CyborgMaster** [comment]
Cool! Does this mean this is done?

**Comment by willbarrett** [comment]
Whoops! Yes, the work has been done, but we usually don't close the issue until the fix has been released. It will be included in the next build.

**Comment by CyborgMaster** [comment]
Awesome, out of curiosity which technique did you use? Remembering the location, or opening on the same screen as the dock?

**Comment by tommoor** [comment]
We've gone with opening on the same screen as dock for now, I think it's important that a call starts in the same spot so you always know where to look. I could see us revisiting this though..

**Comment by CyborgMaster** [comment]
Sounds good to me.  Remembering the spot would simply let me customize where that same spot is. Ex: have the dock on the left monitor and open the calls on the right monitor.  

However, right now my use case has them both on the same screen, so what you've got now is perfect for me.

**Comment by tommoor** [comment]
Released :checkered_flag:
