### ISSUE TITLE
Can't add people to team

### ISSUE THREAD

**Issue by alexperri7** [speak/issues#14]
I'm currently unable to add my co-worker to the team I created since he's already made his own account. If I send him an invite, he receives a code to input upon signup but there's nowhere to add the code if you already have an account.

**Comment by tommoor** [comment]
Hey! 

Yep, unfortunately we don't have a way to change between teams just yet - but definitely shows that this is a priority :smile: . For now I can remove their account and they can sign up fresh? Or signup with another email address to use the invite... lmk.

**Comment by alexperri7** [comment]
Hey man!

If you could remove their account that would be great. The email is kyle@foodshootr.com. I can't wait to test it out. And by the way, love the design!

Alexander Perri
CEO/Co-Founder at FoodShootr Ltd.

416-886-0564
www.FoodShootr.com

**Comment by tommoor** [comment]
@alexperri7 done, hope it works now!

**Comment by rjohnson426** [comment]
@tommoor would you also be able to deactivate my account so I can also join a team that was shared with me. 

Thanks

**Comment by tommoor** [comment]
@rjohnson426 emailed you for confirmation

**Comment by tommoor** [comment]
Merging with #27
