### ISSUE TITLE
Dock gets unnecessary scrollbars with mouse plugged in

### ISSUE THREAD

**Issue by CodzDev** [speak/issues#140]
### Hello,

I'm here to report a bug on speak,

**Mac version** OSX 10.10.5
**Speak version** 0.5.3 (23) 

The __speak.io dock__ appearance change when I plug my razer mouse on my computer and when i unplug it the interface become clear again.

![capture d ecran 2015-08-31 a 11 56 35](https://cloud.githubusercontent.com/assets/7657895/9576592/5c563d28-4fd9-11e5-8337-3d0c8e7c2252.png)

**Comment by tommoor** [comment]
It seems like having your mouse plugged in is forcing scrollbars - does this happen in other apps such as your web browser as well?

**Comment by CodzDev** [comment]
Yes do it in all other apps but for the ergonomics of the "speak's dock" is not good because a lot of persons haven't got an official apple mouse.. Sorry for my bad english ^^

**Comment by tommoor** [comment]
@CodzDev this should be all fixed up in todays release 0.6.0 on Mac :smile:
