### ISSUE TITLE
Add ability to select output device by name

### ISSUE THREAD

**Issue by sschinkel** [speak/issues#141]
Only "Default" and "Built-In" are listed. Skype shows much more, as does OS X's own Sound Preferences. Plantronics microphone is listed though.

**Comment by tommoor** [comment]
Hey @sschinkel thanks for the report! In your case built-in should work correctly, we'll be improving these options shortly :smile:

**Comment by sschinkel** [comment]
@tommoor Yeah, built-in is working okay. But I'm afraid it's less useful for one of my team mates this way, and if one of my team mates isn't using it, it probably won't be used at all. I hope it'll be showing other speakers than 'built-in' soon, would love te able to use this for my team!

**Comment by tommoor** [comment]
@sschinkel happy to let you know we're testing a fix for this internally and hope to get it in the next app release :smile: 

![image](https://cloud.githubusercontent.com/assets/380914/10861664/e9974c54-7f45-11e5-817c-5ffa09bd5b66.png)

**Comment by sschinkel** [comment]
Thanks! Awesome that a fix for this is on the way, will check it out once there's a new release!

**Comment by tommoor** [comment]
@sschinkel released just now on Mac, Linux will be updated later today, Windows within a week :smile:

**Comment by sschinkel** [comment]
Installed the update! Have to wait for my teammates to do the same though.. :)

**Comment by willbarrett** [comment]
Hey all - Linux will actually be tomorrow :)
