### ISSUE TITLE
Feature : Screen sharing (double screen) - Have the choice

### ISSUE THREAD

**Issue by CodzDev** [speak/issues#142]
### Hello,

I have a double screen and my coworker doesn't see very well my screen share because he has got a little screen. It's pretty good to have the double screen view but for the little screen's users it would be interesting to have the choice of the screen we wan't to show.

_Codzdev_

**Comment by willbarrett** [comment]
Hey there - this is actually a duplicate of https://github.com/speak/issues/issues/72. We're working on it!

**Comment by CodzDev** [comment]
Sorry ..

**Comment by willbarrett** [comment]
No worries! Thanks for the report!
