### ISSUE TITLE
Bug : Screen-sharing cursor (double-screen)

### ISSUE THREAD

**Issue by CodzDev** [speak/issues#143]
### Hello,

I'm using the screen sharing in double screen with my coworker. And I noticed that when he's on the left screen his cursor is on the right screen.

Thank's for your support !

**Comment by tommoor** [comment]
Hey there, sorry unfortunately I'm not understand the issue - do you have a screenshot perhaps?

**Comment by CodzDev** [comment]
Sorry I haven't... My coworker has got double screen and when he does a screen sharing and would show me something on his right screen, his cursor is on the left screen for me. And when he would show me his left screen I can't see his cursor.

**Comment by tommoor** [comment]
Understood! As we don't officially support multiscreen sharing yet I'm going to merge thsi in with #72 which when implemented would fix this bug too :smile:
