### ISSUE TITLE
Dock doesn't unhide reliably when hidden

### ISSUE THREAD

**Issue by benkuhn** [speak/issues#145]
I leave Speak hidden most of the time so it doesn't distract me, hide scrollbars, etc. The only problem is that often when I actually want the Speak dock it doesn't show up for some reason--I move my cursor over the right edge of the screen but the dock doesn't slide out.

I'm not sure what's happened here (whether Speak crashed in the background, or just some piece of state is weird), but I fix it through some combination of launching the Speak app via Spotlight, hitting the "show dock" shortcut, and slamming my mouse to the right of the screen. Sorry I can't be more informative.

**Comment by tommoor** [comment]
Hey Ben, thanks! That's pretty helpful, I've been working on some improvements in this area that will be wrapped into the next release (likely Thu). 

One thing it would be good to know next time this happens, is Speak definitely still running? And if it is, is it using more CPU than it should? 

Thanks!

**Comment by tommoor** [comment]
Hey Ben, this should be resolved in todays release 0.5.4 - let me know if you continue to see this issue :)
