### ISSUE TITLE
Error while checking for updates

### ISSUE THREAD

**Issue by mull** [speak/issues#147]
Version: Version 0.5.1 (21)
OS: OSX 10.10.14

This happened while Speak itself (I bet) was checking for updates automatically. I wasn't sure if it was looking for updates or if my version was up to date, so I manually clicked "Check for updates" in the menu. That got me an error screen, ending in "Try again?". The auto-update did end up working just fine. Maybe the button could be disabled while a check/update is already in progress.

PS. The "Try again?" copy was a bit confusing. Did it mean "Click OK to try again" or "Perhaps you could try again?". IIRC there was only one "OK" button so with a bit of though the latter was the only logical meaning, but the copy could be more obvious. :)

**Comment by awsmsrc** [comment]
hey @mull the button should actually be disabled during this phase already...???

When you say an error screen do you mean a pop up window, or a screen within the app?

**Comment by mull** [comment]
Perhaps it wasn't disabled upon update back in 0.5.1? Anyhow it was definitely clickable. The error screen was a native OSX popup.

**Comment by awsmsrc** [comment]
ok thats helpful, I have an idea what may have happened here... I'll investigate

**Comment by tommoor** [comment]
@mull you're right, we used to disable the menu item and change it to "downloading update" - this logic got lost when we moved the menu out of the tray icon. We'll bring it back!

**Comment by tommoor** [comment]
Thanks @mull - all fixed up in todays release (0.6.0) - see all of the details here:

https://speak.io/changelog/
