### ISSUE TITLE
Idle Away Triggers Way too Fast

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#151]
Right now it appears that idle triggers after about 30 seconds.  I would like this to be around 5 minutes, or even better, something that is customizable in the settings.  30 seconds is simply too short.  We use auto answer almost exclusively and around half the time we still have to have it ring and answer because we have been reading code for 30 seconds (which happens all the time).

**Comment by tommoor** [comment]
Hey there, I feel your pain - we might look at increasing this a little more, the aim of this is that you should never click on someone to find that they are no longer at their computer. Having to occasionally answer a call when you're at the machine we think is a better compromise than having people talking into an empty room :smile:

**Comment by CyborgMaster** [comment]
Interesting point.  I think there is a good philosophical discussion to be had here that is critical for Speak and what it is trying to accomplish.  Let me put forth my views on the "empty room vs. ringing phone" question.  

I don't think talking to an empty room is that big of a deal.  The analogy our team is going for is a virtual office.  We are trying to make it seem as if we are working in the same room, even though we are remote.  If we are in the same room, I could easily start talking to my coworker, only to find out that he is not there, in which case I would simply try again later.  The ringing is what really breaks down the "in-office" feel.  There is no way that we would be in the same room, and I would have to wait for my co-worker to "answer" my attempt to speak to him before I could start talking.  So we would prefer to error on the side of accidentally starting a call when they are not there, rather than forcing a ring even though the are there (and just haven't moved the mouse in a bit because they are reading something).  

Now of course this analogy breaks down in a few places that are worth considering, and in a few ways that can make Speak better than a physical office.  One might argue that starting an audio call is not like talking to someone in a room, because when you starting talking in person, you would most likely look over at them and see they are not there, as opposed to sitting there talking into the void, wondering if they are thinking about your question or are in the bathroom.  This exact problem is why we are also asking for the ability to auto start video ( #131 - see that issue for the discussion around privacy), which would then allow you to literally see if they are there.  Then if the team (or an individual) chooses to operate without turning on auto video, then we are deciding to talk to each other across the room without turning our heads, so to speak, in which case we also wouldn't know if they are there in real life either.  

The other thing that these status bubble attempt to give is an at a glance view (without starting a conversation) of who is and who is not available right now, which is better than a physical office and a place where Speak can improve on brick and mortar.  However, to convey this information I think it is critical for a user to be able to adjust the timeout to their common usage patterns.  Some people may do a lot of research and therefore may often go 5-10 minutes of reading without touching the mouse, while others may be focused on something much more interactive and rarely go more than 10 seconds without touching their computer.  

That being said, @tommoor, I wonder what your opinion is on this.  I feel that starting a call when someone isn't there is not a problem.  Why do you feel that it is important that you can never click on someone when they are not at their computer?

**Comment by tommoor** [comment]
I think the biggest thing we've learnt over the last couple of years is that every team is different. For some the auto connect into an empty room is no biggy, for others it completely kills the idea of using the product because of privacy or embarrassment issues...

Our approach in Speak has generally been to choose a nice default and provide settings to tweak for your team/personal preferences. Personally I'm reluctant of having a setting to change the idle time on an individual basis as it's predictability is key to understanding the status of a person. (Having said that, I agree that we probably have it a little short at 30s).

You can actually stop the app putting you in call mode when it detects idle in the settings under "general" > "Disable instant audio when idle/away". Perhaps this is all the AllyDVM team needs to get the experience you want? :smile:

**Comment by CyborgMaster** [comment]
We will disable the auto idle for now.  I agree it is closer to what we want.  That being said, we do miss something with that turned off, the ability to leave a call-me-back bubble.  Right now if they are idle and don't answer, it leaves a little red icon that says they tried to call you.  If there was a manual way to "poke" someone so they would call me back, then I think we wouldn't miss a thing having auto-idle off.

**Comment by tommoor** [comment]
@CyborgMaster we've doubled the away time in todays release (0.6.0) - see all of the details here:

https://speak.io/changelog/

**Comment by CyborgMaster** [comment]
Cool Thanks!
