### ISSUE TITLE
Dock shows scrollbar when hovering over bottommost avatar

### ISSUE THREAD

**Issue by laserlemon** [speak/issues#153]
This is while using my built-in trackpad rather than a mouse, which I hear may have some unwanted scrollbar effects of its own.

![dock-scrollbar](https://cloud.githubusercontent.com/assets/34264/9878644/bf6e5b48-5b91-11e5-9baf-3184f7d42cef.gif)

**Comment by tommoor** [comment]
Thanks Steve! We have a fix for this on a branch, I'll make sure it's in the next release :)

**Comment by laserlemon** [comment]
:+1:

**Comment by laserlemon** [comment]
I just like sending animated GIFs. :)

**Comment by tommoor** [comment]
Thanks for the report @laserlemon , this has been fixed in todays release (0.6.0) - see all of the details here:

https://speak.io/changelog/
