### ISSUE TITLE
Make “Report an Issue …” item available when Dock icon isn’t.

### ISSUE THREAD

**Issue by sellout** [speak/issues#154]
Currently, “Report an Issue …” only exists in the app menu bar, which is only available when the Dock icon is enabled. There should be some way to get to this when only the Menu Bar icon is enabled – perhaps either through the menu attached to the Menu Bar icon, or the menu attached to the user’s icon.

**Comment by tommoor** [comment]
Thanks @sellout, this has been fixed in todays release (0.6.0) too...

https://speak.io/changelog/
