### ISSUE TITLE
Docked app stops hiding periodically.

### ISSUE THREAD

**Issue by sellout** [speak/issues#155]
This seems to happen whenever #150 is triggered, among some other times. I have to open preferences, and toggle hiding off and on again … that _sometimes_ works, but perhaps less than half the time, and if it doesn’t work, doing it repeatedly doesn’t help, so I have to restart Speak.

**Comment by tommoor** [comment]
Thanks for the report, this has been fixed in todays release (0.6.0) - see all of the details here:

https://speak.io/changelog/
