### ISSUE TITLE
Show who's who on hover

### ISSUE THREAD

**Issue by laserlemon** [speak/issues#156]
It would be nice to see each user's name/info on hover, especially for those without avatars. I have no idea who the "D" is in my list.

![dock-user-hover](https://cloud.githubusercontent.com/assets/34264/9888084/0eccbf98-5bc1-11e5-9b81-5f0c73191a7b.gif)

**Comment by tommoor** [comment]
Totally agree, we'd like to add this - it's actually already tracked under #117 so going to merge this issue in there :smile:

**Comment by laserlemon** [comment]
Thanks!
