### ISSUE TITLE
Option to auto answer with the microphone muted

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#159]
Suggestion came through email support. The idea would be that the user could still speak their message, but the called user's privacy is maintained until they want to start transmitting.

**Comment by ericbieller** [comment]
Pretty interesting idea. Is it much better than simply switching to call mode though? After all, it's there for times when you need more privacy.

**Comment by tommoor** [comment]
The feature I've been playing with also provides this in a different way :wink:

**Comment by tommoor** [comment]
Closing for now - this is probably one too many options and is covered by simply placing the app in call mode closely enough.
