### ISSUE TITLE
Minor UI Bug: When the error banner is added to the "Join Team" sign up form, the form overhangs the "card" (see screenshot)

### ISSUE THREAD

**Issue by levinelson** [speak/issues#162]
<img width="461" alt="screen shot 2015-09-22 at 8 49 05 am" src="https://cloud.githubusercontent.com/assets/3728911/10020182/21b57bcc-6107-11e5-9f1e-5a1393685905.png">

**Comment by tommoor** [comment]
Thanks Levi, I've moved this issue over to our website repo :smile: 

https://github.com/speak/website/issues/82
