### ISSUE TITLE
Speak in System Tray

### ISSUE THREAD

**Issue by saenzramiro** [speak/issues#164]
It would be great if Speak opens in System Tray, and if the user clicks in the close the windows of Speak, keep opened.

Now if you close the windows, close Speak.

I'm using Windows 7.

**Comment by tommoor** [comment]
Had another vote for this functionality from Travefy,

> Would like to be able to close the main window and keep the app open.

**Comment by tommoor** [comment]
And in support again... :smile: 

> When i minimize the screen, i would like if speak app go into the taskbar with speak icon. I love the concept of docking. Bringing mac func to windows. :D

**Comment by tommoor** [comment]
Thanks, we've fixed this in 0.6.0 today :smile:
