### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by saenzramiro** [speak/issues#165]
I noticed the volume of voices in Speak are lower than others (Hangouts, Skype, etc). Also I cannot increase the volume in the options.

I'm using Windows 7.

**Comment by tommoor** [comment]
Hey @saenzramiro - are you able to adjust the volume of Speak upwards in the Windows audio settings?

**Comment by tommoor** [comment]
Hey @saenzramiro - I was able to reproduce this on a Windows machine recently. I found that this helped:

- Click on your user icon
- Click 'settings'
- Go to 'Audio/Video'
- Make sure that your microphone is selected and not 'default'

Let me know if this helps? :smile:

**Comment by tommoor** [comment]
Closing in favor of #169
