### ISSUE TITLE
Shortcut conflict

### ISSUE THREAD

**Issue by rnbparty** [speak/issues#170]
Hi, first of all thanks for pretty good and simple soft. 

If Speak is turned on shortcut CMD+OPTION+0 in Google Docs doesn't work even if all Speak shortcuts are turned off. As soon as Speak is turned off same shortcut works fine. 

![screenshot 2015-10-04 12 27 50](https://cloud.githubusercontent.com/assets/996090/10267196/65899528-6a93-11e5-99eb-5612045dbd90.png)

**Comment by tommoor** [comment]
Thanks Kirill, great find - we'll get this fixed up!

**Comment by tommoor** [comment]
Thanks for the report, this has been fixed in todays release (0.6.0) - see all of the details here:

https://speak.io/changelog/
