### ISSUE TITLE
Lost ability to hide offline team members 

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#171]
Looks like in the latest release (0.6.0), we lost the ability to hide offline team members.  You used to be able to show everyone, or to hide offline members.  Now you can show everyone or only starred people.  

I would like to request to be able to hide offline members as a separate check box.  There are a few key people on our team that only sign in to speak from time to time and it's great to see at a glance if they are online, but most of the time they aren't there and I don't really need their picture with a black circle there 90% of the time.  Right now the only way for me to hide them is to star everyone but them, which works fine, but then also hides them when they are online.  

If we could have the "hide offline team members" checkbox back in addition to "show only starred people" then I would be able to configure it to my liking.

**Comment by tommoor** [comment]
@CyborgMaster I think we should add this option back, you're right.

**Comment by CyborgMaster** [comment]
Cool. Thanks!

- Jeremy

**Comment by tommoor** [comment]
We've just release 0.6.1 which restores this option, amongst other things :smile:  https://speak.io/changelog/

**Comment by CyborgMaster** [comment]
Looks great thanks.   I quick bug that I found though: when I mark myself as offline in the quick bar, I also disappear and have to open the main window to change my status.

**Comment by tommoor** [comment]
Whoops, we'll get that tweaked for the next release!

**Comment by CyborgMaster** [comment]
Cool thanks.
