### ISSUE TITLE
Support USB connected speakerphones like Jabra 510

### ISSUE THREAD

**Issue by danaspiegel** [speak/issues#173]
The only way we can use this device as a speaker is to configure it in system preferences.
![screen shot 2015-10-07 at 9 45 45 am](https://cloud.githubusercontent.com/assets/6631/10339220/425d6a4c-6cd8-11e5-9f5f-00d472f3dc61.png)
![screen shot 2015-10-07 at 9 45 53 am](https://cloud.githubusercontent.com/assets/6631/10339219/425b8768-6cd8-11e5-8899-2845986c87fc.png)

**Comment by tommoor** [comment]
Hey Dana! You should be able to use the headset output by selecting "Built-In" - the wording here isn't clear for sure and we're going to add the ability to specifically choose an output device by name in a release soon

**Comment by danaspiegel** [comment]
yes, that works. however I don't want to have to change my system input/output just for using with speak. as with Skype, I'd like to configure speak to use independent audio in/out from the rest of my system.

**Comment by tommoor** [comment]
Hmm, okay - you should be able to select "Built-in" and not have to touch the system settings so we'll take a look at this. It sounds like it's working in the same way as Default if you need to change elsewhere..

**Comment by tommoor** [comment]
I'm merging this in with #141 as they are the same issue by different names :smile:
