### ISSUE TITLE
Screen-share one window only

### ISSUE THREAD

**Issue by mhlavac** [speak/issues#177]
I am running mainly dual screen layout (sometimes even triple screen layout) and if I share the whole screen no-one really sees anything. It would be awesome if you could add some feature as Google Hangouts, appear.in have.

Appear.in requires google extension in order to be able to share screen, maybe the same thing could be reused? Not sure what is available in Electron.

![image](https://cloud.githubusercontent.com/assets/743421/10403143/f5248d5c-6ec9-11e5-84e3-9e2a19b73c3d.png)

**Comment by willbarrett** [comment]
Hey @mhlavac - thanks for the report. We're working towards having this ready. We have an open issue for this already here https://github.com/speak/issues/issues/72, including a proposed design. We're waiting on a pull request (https://github.com/atom/electron/pull/2963) to be accepted by Electron so we can get this out to you. Hopefully it won't be much longer!
