### ISSUE TITLE
Had to restart app after changed mic

### ISSUE THREAD

**Issue by stevenbristol** [speak/issues#179]
1. I opened Speak for the first time.
2. I changed the mic in preferences to my external snowball mic.
3. Started a call (with video)
4. The other person could not hear me.
5. Restarted Speak and then it worked fine.

**Comment by minciue** [comment]
I'm running into the same issue. If I start Speak prior to plugging in my headphones, I can't hear anything through them and I can't be heard either. 

I tried changing the microphone and speaker settings in Speak, but other than restarting the app nothing works.

**Comment by tommoor** [comment]
Hey both, are you also using Skype? We think this is a conflict between the two applications

**Comment by stevenbristol** [comment]
This problem did seem to go away when I closed Skype. I was able to change audio while a video was taking place, with Skype open.

@minciue does not keep Skype open.

**Comment by stevenbristol** [comment]
It looks like 0.6.1 (29) fixed this! Thanks!

**Comment by tommoor** [comment]
Thanks @stevenbristol !
