### ISSUE TITLE
On Mac OS X El Capitan I cannot see team member status, they all appear offline

### ISSUE THREAD

**Issue by fzancan** [speak/issues#181]
And when calling them the call status popup does not show up anymore.
FZ

**Comment by tommoor** [comment]
Hey @fzancan - could you try restarting the app? We did some maintenance at the weekend that might have affected the online/offline status here.

Thanks!

**Comment by NicParry** [comment]
I'm still experiencing this issue, even after restarting the app

**Comment by tommoor** [comment]
Hey Nic, I took a look at your team - it does look like nobody is online at the moment

**Comment by fzancan** [comment]
Hi Tom, after rebooting my Mac the nth time everything seems to be back in
place right now.

Best,

Fede

Il giorno mar 13 ott 2015 alle ore 08:00 Tom Moor <notifications@github.com>
ha scritto:

> Hey Nic, I took a look at your team - it does look like nobody is online
> at the moment
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/speak/issues/issues/181#issuecomment-147614282>.
>
-- 

Federico Zancan

Respect | Work Hard | Achieve

**Comment by awsmsrc** [comment]
Im 99% sure this was related to some backend issues.

I'm going to close the issue and will reopen if reported again without those issues
