### ISSUE TITLE
Team Vanished!

### ISSUE THREAD

**Issue by andrewwatson** [speak/issues#183]
I created a new team and invited a coworker.  They joined up and saw my avatar but I never saw theirs.  I signed out and back in again and suddenly the team I created is gone but I see avatars for everyone on the slack team I authenticated against.  

The Slack integration was strange.  I signed in using one team but then the team that was imported was another team... 

This was on a mac running 10.8

**Comment by tommoor** [comment]
Hey @andrewwatson - it sounds like you have two accounts that are conflicting, could you email howdy@speak.io with the email address you are using and the team names? We'll take a look and get that fixed up :smile:
