### ISSUE TITLE
Lost ability to see which team members are on a call

### ISSUE THREAD

**Issue by megmo** [speak/issues#184]
Before this most recent update, when team members were on a call their avatars would overlap (and I think move a little bit?) to show that they were on a call together. This was helpful to avoid trying to call someone who was already on a call, but I don't see that it happens anymore after the latest update.

It would be great to have this option back at some point.

**Comment by tommoor** [comment]
Hey @megmo ! You're right we removed this functionality in favor of having the dock be simpler, like a quick launch bar. However you can still see folks that are in a call as they have an orange indicator and the main app window shows the ongoing calls display :smile: 

Hope this helps!
