### ISSUE TITLE
Scroll bar appears in dock

### ISSUE THREAD

**Issue by benkuhn** [speak/issues#187]
![image](https://cloud.githubusercontent.com/assets/304831/10467072/958df514-71ac-11e5-9502-b23540e07fef.png)

I suspect this is related to the fact that I use an external monitor, but couldn't reproduce it in 5 minutes of restart/disconnect/reconnect combinations. I'm on OS X 10.10.5 with a Retina MBP 15". Restarting Speak fixed the issue.

(You guys must love my non-reproducible bug reports! Sorry :P This isn't a big deal at all, but hopefully it's at least a little bit helpful...)

**Comment by tommoor** [comment]
Hey! When you scrolled was there another face down there? Like perhaps the dock was simply sized too small?

**Comment by benkuhn** [comment]
Oops! Yes, the actual problem is just that the scroll bar didn't go away, but that may have been my mouse getting funny ideas. Sorry for the noise!

**Comment by benkuhn** [comment]
Hmm, ok, it happened again and it's definitely sticking around even though my mouse is fine. When this bug is occurring the scrollbar is also larger than it otherwise is (a thick opaque oval as opposed to a thin transparent one). I've left Speak in the scrollbar-ified state in case there's any other info I can supply.
