### ISSUE TITLE
Choose which screen is shared with Multiple Desktops

### ISSUE THREAD

**Issue by john-landgrave** [speak/issues#188]
When doing a call on a machine with Multiple Desktops, we're seeing different behavior on different OSes. On Linux (Mint) when I screenshare it shares both of my screens in the arrangement that I have them. When team members (on OSX) share it only shares their primary monitor and they don't have the option to change it.

An option to share either screen, or at least to make the screen on which the call window is located shared would be great.

**Comment by willbarrett** [comment]
Hey John - this is our most requested feature. We're currently blocked upstream, but we expect that a fix for this won't be a long time coming. Here's the existing issue, so you can follow it: https://github.com/speak/issues/issues/72

Closing this as a duplicate.
