### ISSUE TITLE
Remember which group was selected between restarts

### ISSUE THREAD

**Issue by john-landgrave** [speak/issues#189]
When I select a Team from the drop-down, this preference is not saved if I close the program (or restart my computer) and then bring the program back up.

**Comment by willbarrett** [comment]
Hey John - this should be in our next release :)

**Comment by tommoor** [comment]
We've just release 0.6.1 with a fix for this and lots of other goodies! https://speak.io/changelog/

**Comment by john-landgrave** [comment]
Thanks everyone
