### ISSUE TITLE
Unable to connect audio after first signup

### ISSUE THREAD

**Issue by jrauh** [speak/issues#19]
When I click on a teammate, and select Instant Audio, I am unable to communicate with them. Nothing happens.

**Comment by willbarrett** [comment]
Hey @jrauh - sorry for the issue you're seeing - I'm looking into what might be happening right now.

**Comment by willbarrett** [comment]
@jrauh - looks like your clients may have wandered out of synch from our server. Would you both mind qutting + re-starting the app? This might resolve the issue for you in the short term while we figure out the root cause.

**Comment by willbarrett** [comment]
We've deployed a fix for this - let us know if the problem continues!
