### ISSUE TITLE
Unable to join calls, and incorrect contact status

### ISSUE THREAD

**Issue by aeromusek** [speak/issues#193]
This morning, I experienced some very odd behavior.

* Both users were signed into the Speak app already and had been for several days
   * My computer had been on all night
   * Contact's computer went to sleep overnight
* I showed as online to my contact
* My contact showed as offline to me

User steps:

1. I clicked my contact's icon to initiate a call
2. Contact said I showed as in a call, but he never received it
3. Contact restarted Speak, and I still showed as in a call
4. I clicked my contact's icon a second time
5. He received a call request, but clicking accept did nothing. Eventually the request timed out and disappeared
6. He clicked my icon
7. I received a call request, but clicking accept did nothing. Eventually the request timed out and disappeared
8. I restarted Speak
9. He clicked my icon
10. I received a call request and was able to answer as usual

**Note: the calls after this have all experienced the garbled audio in #192)**

**Comment by tommoor** [comment]
@aeromusek we're investigating this as a matter of priority, thanks for the report - we believe this is a backend issue

**Comment by aeromusek** [comment]
@tommoor wonderful! Please let me know if there are logs or other items I can provide to help the effort

**Comment by tommoor** [comment]
@aeromusek we've rolled out a tentative fix for this one, keeping a close eye. If you still have team mates that are in the wrong status then signing/out back in will reset this.

**Comment by aeromusek** [comment]
@tommoor I'll let you know if I see any further weirdness!

**Comment by tommoor** [comment]
We're very confident this is rectified, please reopen if you see the same issue again :smile:
