### ISSUE TITLE
Dock re-appears even though its turned off when dis/connecting a second monitor

### ISSUE THREAD

**Issue by dan-james-deeson** [speak/issues#194]
When the Dock feature is turned off (Appearance -> Dock shows -> no one), it comes back whenever I connect or disconnect a second monitor.

On a related note, if you have two monitors, arranged left and right of each other, set the dock to appear on the right side of the left screen and turn on auto hide then when the dock is hidden it just appears on the left side of the right screen rather than actually disappearing.

I'm using a Mac, with Yosemite.

**Comment by tommoor** [comment]
Hey Dan - thanks for the report! I'll take a look into that this morning.

The second issue is also covered here, https://github.com/speak/issues/issues/119

**Comment by dan-james-deeson** [comment]
Typically - now I've gone and reported the problem I can no longer replicate it. Hopefully you can! And if not then I'll try and some find better steps to reproduce.

**Comment by tommoor** [comment]
I've reproduced the issue and added a fix for the next release, thanks for the report!

**Comment by tommoor** [comment]
We've just release 0.6.1 with a fix for this and lots of other goodies: https://speak.io/changelog/
