### ISSUE TITLE
No in-call UI during first call after install

### ISSUE THREAD

**Issue by michalkopanski** [speak/issues#195]
This has happened to me on two separate OSX machines, with different OS versions:

- 10.10.5 (14F27)
- 10.9.5 (13F1096)

I download/install Speak and call get a call from a team member. I accept the call, but the in-call UI does not appear, so I cannot end the call, start a video cal, or share screen.

The user list shows the teammate as offline (although he's online). After restarting the app, it works as expected.

**Comment by tommoor** [comment]
Hey Michal,

We're investigating this now and tracking in #193 - it appears there are some backend issues that are causing this to happen temporarily

Please bear with us :smile:
