### ISSUE TITLE
Too easy to unintentionally send emails to offline contacts

### ISSUE THREAD

**Issue by callovarne** [speak/issues#196]
# Steps

1. move the mouse pointer over an area near the edge of the screen
2. unintentionally hover over Speak's hidden UI trigger zone
3. click on an _offline_ Speak contact when an app beneath it was the intended click target

# Expected behavior

Either no email is sent, or additional user interaction is required before sending.

# Actual behavior

An email is sent to the offline contact.

# Notes

* It's not clear that clicking an offline contact issues an email.
* If a Speak contact is offline, it's probably for a good reason. Why would they want to get email from Speak where a personally drafted email would be more appropriate?
* Even if the click on an offline contact was intentional, a user might not want to spam a contact if they didn't immediately see the contact was offline.

**Comment by tommoor** [comment]
Just to let you know, we've fixed this up in todays release on Windows. It'll be in the next Mac release too :smile:

**Comment by callovarne** [comment]
Awesome! On the bright side, several people learned what Speak is when I
went click-happy. ;D

**Comment by tommoor** [comment]
Well, that was kind of the idea ;) Either way we've made this interaction clearer on Windows and it'll be out in the next Mac release very soon. Closing for now!
