### ISSUE TITLE
Multiple cameras on Mac appear with the same name

### ISSUE THREAD

**Issue by dceddia** [speak/issues#197]
In Preferences > Audio/Video, the Camera dropdown shows 2 cameras with the same name.

![image](https://cloud.githubusercontent.com/assets/505704/10547781/868bf5f2-7404-11e5-9e93-dec2e8a5b31e.png)

I'm using a 13" macbook connected to a 27" display, and both have cameras. Skype differentiates between the 2 cameras like this:

![image](https://cloud.githubusercontent.com/assets/505704/10547836/c0a0531e-7404-11e5-8778-952f51ea674b.png)

Maybe you could add something similar?

**Comment by tommoor** [comment]
Great bug Dave, thanks for reporting! I think I might know what's causing this one

**Comment by tommoor** [comment]
Now fixed, thanks for the report!
