### ISSUE TITLE
Speak seizes focus frequently

### ISSUE THREAD

**Issue by benkuhn** [speak/issues#199]
I just had an issue where every ~5 seconds, Speak would seize focus without any bringing windows to the front. (Basically this just meant that every 5 seconds the menu bar would change to Speak's, and whatever field I was typing into would stop receiving keyboard input.)

I had milder versions of this issue before, where Speak would seize focus 1-2 times but then stop. Restarting Speak appears to have cleared up the severe version.

I am not connected to an external monitor right now, although I may have connected and disconnected from one since the last time I restarted Speak. Still on my 15-inch rMBP.

**Comment by tommoor** [comment]
Hey @benkuhn - this is occuring when the client reconnects, we just had a spot of downtime that caused the client to reconnect many times in a row. 

The issue will be fixed in the next Mac release, later this afternoon :smile:

**Comment by tommoor** [comment]
We've just release 0.6.1 with a fix for this and lots of other goodies: https://speak.io/changelog/
