### ISSUE TITLE
Joining a channel should automatically broadcast

### ISSUE THREAD

**Issue by tommoor** [speak/issues#2]
**Repro steps:**

- Start the app
- Join a channel and take broadcast mode off
- Leave the channel
- Join a channel
- Broadcast stays off

**Expected behaviour:**

- Broadcast defaults to being back on

**Comment by mull** [comment]
This is how I would expect it to work. If I have chosen to take broadcasting off I would like it to stay off. :)

**Comment by tommoor** [comment]
Good to know! Everyone on our team starts talking accidentally thinking they're broadcasting - we've found anecdotally that if you actively click into a channel then that means you're usually wanting to say something...

**Comment by awsmsrc** [comment]
N/A
