### ISSUE TITLE
I'm subscribed to a ghost team and I can't remove myself.

### ISSUE THREAD

**Issue by mdanieli** [speak/issues#202]
When I signed in the first time, I had a bunch of strangers in my list of contacts. Very disturbing experience. When I look in Preferences, I see that I'm subscribed to an invisible team that I cannot remove myself from.

![screenshot 2015-10-21 14 08 09](https://cloud.githubusercontent.com/assets/798012/10636119/a168ea4a-77fd-11e5-8381-bc13f714785e.png)

**Comment by tommoor** [comment]
Hey Matteo, sorry for the trouble here - first time we've seen this one! It looks like you ended up with a 'null' in your list of organizations somehow, I've removed this now and we'll look into the underlying cause as a matter of priority!

**Comment by tommoor** [comment]
Hey Matteo, we've gotten to the bottom of this one and deployed a fix to stop it happening again - thanks for letting us know!
