### ISSUE TITLE
Speak is initiating calls on its own

### ISSUE THREAD

**Issue by aeromusek** [speak/issues#205]
This has happened three times this morning between myself and a coworker.

It shows on both ends that he is calling me, but he does nothing to initiate the call. One of these occurred while we were already on a call with each other (that we HAD initiated), and it rang while we were still talking.

**Comment by tommoor** [comment]
Hey, we added a new keyboard shortcut in 0.6.2 so that the answer call shortcut now works to re-call the last person you talked to - could this be what is happening here?

**Comment by aeromusek** [comment]
Hmmm...possible! I'll keep an eye out and see if it happens again.

My coworker got tired after three occurrences and moved back to WebEx for the rest of the day, so I haven't had any further mishaps yet :disappointed:

**Comment by tommoor** [comment]
@aeromusek as we haven't had any other reports of this I think it must have been the new shortcut, closing now but feel free to reopen if you disagree

**Comment by aeromusek** [comment]
@tommoor I agree. I had my coworker change the shortcut and this stopped occurring :+1:
