### ISSUE TITLE
Linux client: windows have too much transparency

### ISSUE THREAD

**Issue by minecrafter** [speak/issues#206]
A few examples:

Login: https://i.imgur.com/HJAyW5i.png and https://i.imgur.com/xOeVoM7.png
Client: https://i.imgur.com/iH1gepJ.png

I'm running Ubuntu 14.04.3 LTS amd64.

**Comment by tommoor** [comment]
We've had this reported a few times in Linux (although the first time here, so thanks for the issue!). Right now we're not sure what causes this but we're investigating :smile:

**Comment by willbarrett** [comment]
Hey @minecrafter -thanks for the report! Are you using the default Unity window manager or something else?

**Comment by minecrafter** [comment]
Default Unity window manager.

**Comment by willbarrett** [comment]
Hey @minecrafter - I've got a potential fix for this that will go out in the next release. Hard to tell, as it doesn't duplicate for me.

**Comment by tommoor** [comment]
@minecrafter we just released 0.6.3 and are pretty confident it fixes this issue if you get a chance to give it a try :)

**Comment by minecrafter** [comment]
Excellent! Thanks.
