### ISSUE TITLE
Sidebar should have hover-text for names

### ISSUE THREAD

**Issue by bridger** [speak/issues#209]
A few coworkers only have a letter for their profile picture. Other ones have pictures that are difficult to recognize when they are so small. Hovering over their icon in the sidebar should show their name.

**Comment by MC-Carter** [comment]
I agree. I was expecting to see that feature there already. Would help.

**Comment by tommoor** [comment]
We agree however the framework we're using makes this trickier than usual... we do plan on adding this functionality however!

dupe of #117
