### ISSUE TITLE
Add Hotkey for leave call

### ISSUE THREAD

**Issue by CyborgMaster** [speak/issues#21]
Feature Request.  At the end of a call, there is often a 2-3 second awkward pause as a person grabs a mouse and looks for the hang up button.  There are already global keyboard shortcuts for Speak; if we added one to leave the call, that would make it much quicker.

**Comment by willbarrett** [comment]
Good concept. Any thoughts on what a good key combo would be for now?

**Comment by CyborgMaster** [comment]
Of coures configurable would be ideal, but in the meantime, how about Command-Alt-H for "hang up"

**Comment by ericbieller** [comment]
Nice one, felt the need for this myself.

For comparison, Skype default is cmd+shift+h https://support.skype.com/en/faq/FA12074/what-keyboard-shortcuts-can-i-use-with-skype-for-mac-os-x

**Comment by tommoor** [comment]
CMD+ALT+H would make sense with our current shortcuts... obviously the plan is to make all of these customizable in a future update :wink:

**Comment by theworkerant** [comment]
I dunno about you guys... but for me CMD+ALT+H is default for hide all other windows. 

Also, none of the shortcuts seem to work for me, should I file another issue?

**Comment by willbarrett** [comment]
Good point @theworkerant. Please do file a different issue if all of the shortcuts aren't working for you. Please include as much info as possible, and we'll try to get to the bottom of it!
