### ISSUE TITLE
Unable to toggle between cameras on Preferences-Audio/Video-Cameras

### ISSUE THREAD

**Issue by jjmoney** [speak/issues#213]
I'm on a Mac, El Capitan 10.11. speak 0.6.3 (31). When I start up my built in camera as used and even if I change the drop down to my Logitech external camera the selection switches but it does not start the other camera. There is a workaround - If I close the lid on my laptop it will force the other camera to work.

**Comment by danwu** [comment]
This has been happening to me as well. When external mic or camera has been plugged in, sometimes I have to restart the application to have the new hardware to be picked up, even though they are listed in the mic/camera dropdowns.

**Comment by tommoor** [comment]
Hey both, what happens when you try selecting the second camera - does it show as black or do you see the output of the previous camera?

Thanks!

**Comment by jjmoney** [comment]
It stays on the output of the previous camera.

**Comment by theborch** [comment]
Ditto to what @jjmoney is experiencing here.
MBP, 10.11.1, Speak 0.6.3

**Comment by tommoor** [comment]
Thanks for the report, this is fixed up in todays release (0.6.4) :smile:
