### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by maxengel** [speak/issues#214]
http://cl.ly/image/2J1Z2M3N2c27

**Comment by ribbitsean** [comment]
Same exact problem for me

**Comment by tommoor** [comment]
Thanks guys and sorry for the trouble! The app has been offline and we're battling to bring it back, expect to be able to connect by 9am!

**Comment by tommoor** [comment]
Hey guys, we're back online and looking into a root cause analysis - sorry for the frustration here :(
