### ISSUE TITLE
Positioning works differently based on scaling.

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#22]
Video of bug here: https://www.dropbox.com/s/1gojgkc68375h11/speak.io%20bug.mov?dl=0

This also probably has something to do with dock interaction.

**Comment by kimslawson** [comment]
Seems related to dock position but also screen scale on retina displays. At default scaling it does not occur, but it does occur at maximum scale ("more space"). Further, at other scale factors, Speak seems not to show it's "dock" at all.

**Comment by tommoor** [comment]
@kimslawson please give the latest release a go (0.3.3) - I believe this will solve your issues here!

**Comment by tommoor** [comment]
Marking as fixed unless you let us know otherwise :smile:
