### ISSUE TITLE
Speak People menu Disappeared permanently

### ISSUE THREAD

**Issue by iwaffles** [speak/issues#23]
I've quick the app and relaunched it. I've also turned on/off hiding but I cannot seem to see the people on the left hand side anymore. 

I'd be happy to share any logs or anything if needed!

**Update** It looks like after clicking while holding the cursor on the left hand side to the screen they eventually came back.

**Comment by tommoor** [comment]
@iwaffles you didn't turn on the option to hide the people dock did ya?

**Comment by iwaffles** [comment]
I did, but turning it on and off didn't show anyone at all, even if I
hovered in that area for 20 minutes :-/

Not sure if it was a minor bug or something wrong with my computer, but it
seems to be resolved now.

I think someone tried to call me and then it all disappeared, but I
couldn't exactly tell because I had music on full blast.

**Comment by tommoor** [comment]
We just had a spot of downtime - overloaded our media server so this probably triggered your app to disconnect temporarily too and that could well be what you saw. Next time you can click on the tray icon to see if it the state of the app is 'connecting' or 'online' :smile:

**Comment by iwaffles** [comment]
Bingo, will do!

Thanks Tom!
