### ISSUE TITLE
Improvements to dock when hidden

### ISSUE THREAD

**Issue by tommoor** [speak/issues#25]
We had this lovely video made, however it highlights that when the dock is hidden the interactions are a little more fiddly than we'd like: http://clrsight.co/ih/speak-review.mp4

There's also a point where the user is in a call but the dock is hidden, not showing that.

**Comment by ericbieller** [comment]
As discussed, would also be nice for the dock to hang out a bit after mouse out, so it's not constantly popping in / out.
