### ISSUE TITLE
Not possible to accept invite outside of the new user creation flow

### ISSUE THREAD

**Issue by petedoyle** [speak/issues#27]
Had a coworker say to join so I did.  Slack login failed (see #24), so I created an account via email with no invite code.  It asked me to create a team.  A couple minutes later I got an invite code, but I can't enter it outside of the new user flow.  I also can't delete my account to try again

**Comment by willbarrett** [comment]
Hey @petedoyle - thanks for this! We have an admin function for this, which we expect to be adding to the front end soon. If you let us know what team you should be part of, or what your email address is, we can make sure you get there.

**Comment by petedoyle** [comment]
Awesome, thank you @willbarrett.  pete@whistle.com / invite DBDD24

**Comment by chrismckenna** [comment]
I have the same problem.   Can you help sort me out as well?  
@willbarrett topher@us.ibm.com / invite C3E341

**Comment by willbarrett** [comment]
@petedoyle and @chrismckenna you should be all set.

**Comment by tommoor** [comment]
Hey everyone! We just released this feature in 0.3.0. Open the app, hit "check for updates" and you'll get the new version - you can then login and accept an invite to another team from the preferences window.

Hope this helps
