### ISSUE TITLE
Does Speak (re)-regenerate my Slack auth token?

### ISSUE THREAD

**Issue by theworkerant** [speak/issues#29]
Got an email from Slack:

> A new API token was issued for your graham ...

Was this Speak? If so, does it regenerate existing tokens? If so can it not do that? Speak may not be the only service using that.

**Comment by willbarrett** [comment]
Hi @theworkerant - AFAIK, API tokens are issued by Slack through OAuth on a per-application basis, so this shouldn't affect anything else that you've already integrated with Slack. I hope that helps!

Will

**Comment by theworkerant** [comment]
Thanks! I wasn't sure, there isn't a lot of log info on token generate, just a general notification.
