### ISSUE TITLE
Feature request: Hide floating window on channel inactivity

### ISSUE THREAD

**Issue by mull** [speak/issues#3]
I like having the toolbar there to show who's in the channel, but not when the channel is totally inactive. Preferably it'd work something like this:

- Floating window is visible when app is started / joined channel
- Timer is started
- Any activity (joined channel, talked) resets timer
- When timer reaches `n` minutes the window fades out/hides
- When window is hidden and activity starts again, re-show the window

**Comment by tommoor** [comment]
I can see where you're coming from here. I think it might be a little confusing to have the window just disappear after a certain amount of time. 

What might work and be a little clearer/more consistent would be to have an option to only show the floating window if there are other folks in the channel?

**Comment by mull** [comment]
Mayhaps! I see how it could be confusing, certainly if it was default behaviour. On the other hand the way it is now I have to deal with a floating window that tends to steal focus or be in the way, while showing nothing of interest. OTH I could just click it away... :)

**Comment by ericbieller** [comment]
One downside of having the floating window automatically disappear is that it becomes easier to forget you're in a channel. 

I think you're right @mull I'd say just hide it when you want to stay in a channel but the window is getting in the way.
