### ISSUE TITLE
User online/offling flagging after connection issues

### ISSUE THREAD

**Issue by theworkerant** [speak/issues#30]
Seems like there are some connection issues right now. That's cool, I just wanted to capture this to show what it looks like from a UX perspective (super annoying). Maybe a `debounce`?

https://www.dropbox.com/s/9yim01ax9d60svv/connection%20troubles.mov?dl=0

**Comment by willbarrett** [comment]
Hey @theworkerant - thanks for reporting this! Someone on our team noticed the same thing yesterday, and we're definitely looking at how to get it fixed up. We did a little more scaling this AM, but things should be back to normal for the rest of the day.

**Comment by tommoor** [comment]
This is no longer an issue in the latest release!
