### ISSUE TITLE
Add option to kick another user out of a call

### ISSUE THREAD

**Issue by tommoor** [speak/issues#31]
This is especially useful when you bring someone into instant audio but they aren't there to leave themselves or perhaps don't notice which occassionaly happens

**Comment by tommoor** [comment]
@ericbieller If we have this and other per-user actions we'll have to go back to having the menu open on each individual call user. This might be clearer than before now it has the kick action and leave call?

**Comment by ericbieller** [comment]
@tommoor you know I support it!
