### ISSUE TITLE
Login Loop on Snow Leopard

### ISSUE THREAD

**Issue by udayms** [speak/issues#32]
The app is going to a login loop on Snow Leopard. We get the login window, we click on the login using slack. Type in team name. Type in login credentials and then that window goes away. Nothing happens.

On Yosemite, we get the slack app authorization screen right after giving the slack credentials. That doesnt seem to happen on Snow Leopard.

**Comment by tommoor** [comment]
Hey @udayms, we only support OSX 10.8 or later, sorry about that. I'll be sure to add a note to this affect on the download page!
