### ISSUE TITLE
App appears to be online, but isn't.

### ISSUE THREAD

**Issue by iwaffles** [speak/issues#33]
Speak is online and using version 0.2.9.

Here's a video of the issue:
![screen recording](https://cloud.githubusercontent.com/assets/7333/7620010/970d4a2e-f971-11e4-8329-b9e54772e0c2.gif)

**Comment by tommoor** [comment]
Hey, I believe this is due to running the dock on the left as well. We haven't designed it for this circumstance. Can you confirm that it works fine when the dock is moved? The next release will include the ability to move Speak to the right of the screen

**Comment by iwaffles** [comment]
Same issue regardless of where my dock is.

I can't seem to actually see any faces, either.

**Comment by tommoor** [comment]
@iwaffles one last q, do you know if this was after your machine had been asleep for a period?

**Comment by iwaffles** [comment]
I'm not sure, but likely it wasn't. My machine is like me: it never sleeps.

**Comment by tommoor** [comment]
We're confident this was fixed in 0.3.2 - please reopen if you see it again!

**Comment by iwaffles** [comment]
:+1: will do!
