### ISSUE TITLE
signed up w/out joining a team, can't join team now?

### ISSUE THREAD

**Issue by baseballkyle** [speak/issues#34]
is it possible to join a team after you signup? can't find it if you can.

**Comment by tommoor** [comment]
Hey @baseballkyle this isn't currently possible, we're working on this. To join a team you need to sign up with the same slack account or enter an invite at signup. 

If you have an invite I can delete your account so you can signup again?

**Comment by tommoor** [comment]
dupe of #27

**Comment by baseballkyle** [comment]
Yes, please delete - i do have an invite. Thx!!

Kyle

**Comment by tommoor** [comment]
Please email howdy@speak.io with the email address on your account and we'll get it sorted :)
