### ISSUE TITLE
Product Website doesn't share well on Facebook

### ISSUE THREAD

**Issue by tosh** [speak/issues#35]
It seems like you're missing some open graph meta information love:

fb url linter (see https://developers.facebook.com/tools/debug/og/object/):
![2015-05-13 at 15 15](https://cloud.githubusercontent.com/assets/14825/7622278/ffbdde42-f982-11e4-82e8-e3c70be1e3c2.jpg)

on facebook.com:
![2015-05-13 at 15 16](https://cloud.githubusercontent.com/assets/14825/7622286/13ed3f0c-f983-11e4-9453-4ad2247e6d97.jpg)

**Comment by ericbieller** [comment]
Thanks for reporting! Will get it taken care of :)

**Comment by ericbieller** [comment]
Facebook data has been added, but not too sure why it's unable to scrape any data.

**Comment by tommoor** [comment]
Boo: http://ramsesoriginal.info/2015/03/21/facebook-open-graph-github-pages/

**Comment by ericbieller** [comment]
Snap
