### ISSUE TITLE
No Retina for you (Product Website)

### ISSUE THREAD

**Issue by tosh** [speak/issues#36]
Product website landing page is awesome but missing some retina love:

![2015-05-13 at 15 19](https://cloud.githubusercontent.com/assets/14825/7622340/a0d5a04e-f983-11e4-86ec-f8889e0d3472.jpg)

:D

![no-soup-for-you](https://cloud.githubusercontent.com/assets/14825/7622368/d157f064-f983-11e4-8475-fa9b58800250.gif)

**Comment by tommoor** [comment]
Heh, the retina video was pretty massive. Perhaps we just need to media query it

**Comment by tosh** [comment]
niiiice
