### ISSUE TITLE
Issues when OS X dock is set to left

### ISSUE THREAD

**Issue by jamesbrooks** [speak/issues#37]
When the OS X dock is left orientated speak.io clashes fairly heavily (erratic jumping when mouse-overing), to the point where there are some users that I cannot click at all.

Needs an option to set the position of the speak.io users list.

**Comment by tommoor** [comment]
Hey James! Totally agree, infact we already have an issue tracking this at #10 - we plan for this feature to be in the next release :)

**Comment by jamesbrooks** [comment]
Ah, I had a skim but missed #10. Thanks for the prompt reply @tommoor. :+1:

**Comment by tommoor** [comment]
oh, we're on it!

![fast typing](https://cloud.githubusercontent.com/assets/380914/7623741/47d22c28-f993-11e4-8bbe-f321b3d53298.gif)

**Comment by tommoor** [comment]
We just released this feature in 0.3.0, thanks! http://speak.io/changelog#0.3.0
