### ISSUE TITLE
Preference menu not opening

### ISSUE THREAD

**Issue by mitrakmt** [speak/issues#38]
On a new macbook pro. When I click preferences, nothing comes up.

**Comment by willbarrett** [comment]
Hey @mitrakmt - thanks for the message! did you happen to move the Speak application after opening it? We've been seeing some oddness related to this...

**Comment by mitrakmt** [comment]
Hi Will,

Thanks for reaching out. That's exactly what it was, I moved the
application back then restarted Speak. Then it worked.

Are you all working on bringing down the high CPU usage? I love the
product, but it's an issue when the CPU usage is multiples of a browser.

Keep up the great work,
Mike

On Thu, May 14, 2015 at 5:18 AM, Will Barrett <notifications@github.com>
wrote:

> Hey @mitrakmt <https://github.com/mitrakmt> - thanks for the message! did
> you happen to move the Speak application after opening it? We've been
> seeing some oddness related to this...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/speak/issues/issues/38#issuecomment-102018276>.
>



-- 
Michael Mitrakos
International Business Development @Gigya
www.michaelmitrakos.com

**Comment by willbarrett** [comment]
Awesome! Feel free to move the app - it will work fine, as long as it's not running while you use it. We're working on an installer that will avoid this issue in the future.
