### ISSUE TITLE
undefined user

### ISSUE THREAD

**Issue by smvanbru** [speak/issues#39]
I have an undefined user at the bottom of my team call list. When I mouse-over it, it disappears, so I can't see/do anything with it.

**Comment by tommoor** [comment]
@smvanbru thanks for the report! We're aware of this one and have a fix ready to go out, it should be released later today :smile:

**Comment by tommoor** [comment]
We just released a fix for this in 0.3.0, thanks! http://speak.io/changelog#0.3.0
