### ISSUE TITLE
accepted invite when signing, but doesn't join team

### ISSUE THREAD

**Issue by baseballkyle** [speak/issues#40]
i accepted an invite when signing up, but my teammate says it doesn't show that i have accepted the invite, nor do i see him when i fire up Speak.

**Comment by willbarrett** [comment]
Hey @baseballkyle - sorry about that! Email the address you joined with and your invite code to howdy@speak.io and we'll get you where you need to be.

**Comment by baseballkyle** [comment]
*B2D3BF and baseballkyle@gmail.com <baseballkyle@gmail.com>*

**Comment by willbarrett** [comment]
OK, you've been moved. Looks like there were multiple orgs with the same name, so let me know if you're not in the right one now.
