### ISSUE TITLE
Microphone not working intermittently

### ISSUE THREAD

**Issue by tommoor** [speak/issues#41]
"Sometimes my audio goes dead and nobody can hear me until I restart Speak" - https://twitter.com/IsaacHolmgren/status/598979406330114050

We don't know much more yet. This may occur after a restart

**Comment by electblake** [comment]
+1 I've also tried mute/unmute to no avail.

**Comment by tommoor** [comment]
@electblake thanks the letting us know. It it happens again can you open audio preferences within speak and see if your mic is being detected there...?

**Comment by tommoor** [comment]
We believe that the latest release fixes this issue, http://speak.io/changelog/#0.3.2

Please reopen if you see it again!
