### ISSUE TITLE
Detect resolution change

### ISSUE THREAD

**Issue by ericbieller** [speak/issues#42]
When changing resolution / scaling the dock ends up in the middle of the screen until the interface updates. 

![image](https://cloud.githubusercontent.com/assets/740552/7645009/2b27f730-fa63-11e4-82a7-5b15625204fe.png)

**Comment by tommoor** [comment]
Similar issue reported by email (awaiting further info):
![image](https://cloud.githubusercontent.com/assets/380914/7663775/e40437e2-fb25-11e4-9eef-6a4610c4fc98.png)
