### ISSUE TITLE
Linux client

### ISSUE THREAD

**Issue by ziloc** [speak/issues#43]
Any progress on a linux client?

**Comment by willbarrett** [comment]
Hey @ziloc - thanks for asking. We don't have a timeline right now. As there are further developments, we'll update the thread here.

**Comment by zette** [comment]
Count me +1 for Linux client.

**Comment by ryanjcollier** [comment]
This would be nice as much of our development team uses Linux.

+1

**Comment by codehotter** [comment]
+1

Sqwiggle is the most amazing tool to happen to our team and we were pretty excited to learn about speak.io... Some devs are shy on video, especially working from home without pants on, native app, using slack for chat, still have the tap on shoulder instant audio...

Unfortunately, most of our team uses Linux. I almost talked them into switching to Mac for speak.io and screenhero, but there are some diehard Linux users complaining about Mac Os hotkeys...  No luck.

According to http://stackoverflow.com/research/developer-survey-2015#tech-os Linux is the least used developer OS, but not by far. If there is anything I can do to help bring about a Linux client (like making fewer useless +1 notifications distracting you) please let me know.

**Comment by willbarrett** [comment]
Hey @codehotter - we're on it! This is definitely going to happen. It's only a matter of time and resources at this point.

**Comment by CyborgMaster** [comment]
Out of pure curiosity, do you happen to have a guesstimate as to when this might be available?  We have a guy that prefers to use Linux and would love to use this if it works out.

**Comment by willbarrett** [comment]
We're thinking a beta sometime in the next few weeks. We're focusing on platform support right now. I can't be more specific, but it's definitely 'weeks not months'

**Comment by CyborgMaster** [comment]
That is specific enough for me.  Love it.  Thanks! Keep up the good work.

**Comment by willbarrett** [comment]
Hey All - I just pushed up the first beta version of our Linux client. I've been using it for a while now as it's been under development, but we think it's ready to see some more usage. Here are the download instructions: http://help.speak.io/article/43-speak-for-linux

At the minute, we just have a 64-bit .deb package, but I hope to give non-Debian distros some love in the near future. Looking forward to your feedback!

**Comment by CyborgMaster** [comment]
Super exciting!  You guys have incredible timing.  We have a new hire that starts tomorrow that really wants to use Linux, and now he can use Speak too.

**Comment by willbarrett** [comment]
Awesome! Let us know how it works for them!
