### ISSUE TITLE
Speak intercepts cmd-shift-d (Dvorak Layout)

### ISSUE THREAD

**Issue by WizardOfOgz** [speak/issues#50]
When Speak is open it seems to be capturing the cmd-shift-d keyboard shortcut although nothing noticeable happens. I became aware of this when the shortcut stopped working in other applications (specifically Sublime Text and Atom text editors, where it is used for the "duplicate line" command).

When I quit Speak cmd-shift-d works normally in other applications.

I do not know how to isolate the problem more than this, but I'll help in anyway I can.

**Comment by tommoor** [comment]
Thanks for the report @WizardOfOgz . I just gave this a try now on 10.10.1 and unfortunately it's not happening on this end, especially weird as we definitely don't bind to this combo at all. It's likely that we'll prioritise custom shortcuts soon which would would help to fix this

**Comment by WizardOfOgz** [comment]
@tommoor thanks, I'll continue to look into this locally and let you know if I'm able to figure out what triggers the behavior I'm experiencing.

**Comment by cwhenderson20** [comment]
I am not having this issue with cmd-shift-d, but I am having the exact same problem with cmd-alt-m, which, for me, intercepts the keyboard shortcut for block comments in Sublime Text. Strangely, it also intercepts cmd-shift-h, which is not a keyboard shortcut that Speak seems to be listening for.

**Comment by tommoor** [comment]
Hey Chris, actually cmd-shift-h is bound to leave call - this is miswritten in the preferences window.

**Comment by WizardOfOgz** [comment]
@tommoor OK, my problem might make more sense now...I'm using the Dvorak keyboard layout where the 'D' key is where the QWERTY 'H' key is located. Could it be that `cmd-shift-d` is being interpreted as `cmd-shift-h` by Speak???

**Comment by WizardOfOgz** [comment]
@tommoor My suspicion seems to be correct, that the keybindings for Speak do _not_ respect the keyboard layout (Dvorak in my case). Do you want me to open a separate issue for that?

**Comment by tommoor** [comment]
@WizardOfOgz thanks for the update, I've just gone ahead and renamed this issue to cover your findings :)

**Comment by tommoor** [comment]
All fixed up in todays release, thanks! http://speak.io/changelog/#0.4.1

**Comment by WizardOfOgz** [comment]
@tommoor The keyboard shortcuts in the 0.4.1 release still do not respect the selected input (OSX 10.10.3). I.e. The keyboard shortcuts act as if I am using a QWERTY input instead of Dvorak. 

The ability to customize shortcuts in the app preferences allows me to leave Speak open without disrupting my workflow, so thanks for that!
