### ISSUE TITLE
Hidden dock takes takes space before login

### ISSUE THREAD

**Issue by modkaffes** [speak/issues#53]
I have Speak docked to the left side and set it to auto hide.

Right after a reboot, and before I sign in to my account, there is a space where the docked app should be which when clicked takes out of focus the window that stands there, but doesn't bring up Speak.

Took me a while to figure what's wrong. Check the following clip for a visual demonstration.
[Youtube clip](https://youtu.be/pwPWHGD-DXY)

**Comment by tommoor** [comment]
Hey @modkaffes - thanks for the report! We have a fix for this in the next release which will be either today or tomorrow :smile:

**Comment by tommoor** [comment]
We just released a fix for this, thanks! http://speak.io/changelog/#0.3.2

**Comment by modkaffes** [comment]
@tommoor You're fast, thanks ;)
