### ISSUE TITLE
Microphone un-mutes when a new person joins a call.

### ISSUE THREAD

**Issue by rnstewart** [speak/issues#54]
Steps:

1) Start a call.
2) Click microphone icon to mute mic.
3) Have a new person join the call.

Note that the microphone has been un-muted after the new person joined the call. It should stay muted until the user chooses to un-mute it.

**Comment by tommoor** [comment]
Thanks for the report @rnstewart - we'll get a fix for this in the next update later today!

**Comment by tommoor** [comment]
And, we released a fix - thanks! http://speak.io/changelog/#0.3.2

**Comment by rnstewart** [comment]
Great job! Thanks for the quick fix.
