### ISSUE TITLE
Heads don't move when plugging in an external monitor

### ISSUE THREAD

**Issue by respectTheCode** [speak/issues#55]
On OS X when I plug in an external monitor the heads seem to be moved to a random location on the new screen. Restarting the app or signing out and back in fixes it.

**Comment by tommoor** [comment]
Hey, when you plug in your monitor does it become the default screen with the mac dock etc?

**Comment by respectTheCode** [comment]
I did some testing and switching the default screen does the same thing. I have the heads on the right side of my screen. When i switch to the smaller screen the heads move to be positioned correctly. When I switch back to the bigger screen the heads don't move and end up in the middle of the screen.

**Comment by tommoor** [comment]
Thanks for the details, I think this will be fixed at the same time as https://github.com/speak/issues/issues/42
