### ISSUE TITLE
Custom Keyboard Shortcuts

### ISSUE THREAD

**Issue by tommoor** [speak/issues#59]
We'd like to add the ability to remap the global shortcut keys. This will also allow us to add many more optional shortcuts as they can be changed if they interfere with other apps on the system

**Comment by watt** [comment]
+1 for this. I am a developer, and Command-Shift-H conflicts with the shortcut for the Home button in the iOS Simulator. That's a complete dealbreaker for our team.

**Comment by tommoor** [comment]
Hey @watt that's really good to know, we'll be prioritizing this and have already started working on it

**Comment by willbarrett** [comment]
Assigning to @tommoor for UI polish.

**Comment by tommoor** [comment]
Happy to say that we now have custom global shortcuts! Woop, see the release notes here:

http://speak.io/changelog/#0.4.1

**Comment by bountin** [comment]
\o/
I just wanted to complain that "Toggle the dock" hides IntelliJ's "Inline Refactoring" shortcut and I was really surprised that it was fixed literally three days ago. Great work guys!

By the way: Checking for Update did not pick up 0.4.1 from 0.4.0. Intentionally or not? Updating via the website download worked nevertheless.

**Comment by willbarrett** [comment]
Thanks @bountin! Glad that we could help! Yup, we disabled the auto-upgrade from 0.4.0 to 0.4.1 for some stability reasons, but 0.4.2 should be coming out today.
