### ISSUE TITLE
Allow user invite field to take multiple email addresses at once

### ISSUE THREAD

**Issue by tommoor** [speak/issues#63]
Right now the invite field at the top of the team list only allows a single email to be entered at a time, this is tedious.

We should allow multiple emails to be entered, separated by commas, semicolons or spaces.

**Comment by awsmsrc** [comment]
theres some UI things to discuss here

E.G imagine there is already an invite for email2@example.com and i submit the following

```
email1@example.com, email2@example.com, email3example.com
```

**Comment by tommoor** [comment]
If there is already an invite then that can be a silent failure. If there is an invalid email address then we can fail the entire request and show an error banner.

Does that work?

**Comment by awsmsrc** [comment]
it does, but the client will need to either respond to three creates or we will need a batch message type?
thoughts?
