### ISSUE TITLE
Reconnect-Last-Session hot key

### ISSUE THREAD

**Issue by RalphMickelson** [speak/issues#64]
Here is very frequent scenario for me:
* Conversation just finished.
* Tap Cmd+Shift+H (Love that feature! Thank you!)
* Think of *one-more-thing* I forgot to mention.
* Instinctively, I hit Cmd+Shift+H again (of course, it does nothing)
* Grab the mouse, find the associate I was just chatting with, and reconnect.

A **Reconnect-Last-Session** would be a great feature. It could be assigned to another hot key, but I think just re-using the Hang-Up hot key, when not connected, could just *un-hang-up*; like a toggle switch.

**Comment by tommoor** [comment]
Hey @RalphMickelson,

Totally agree - I thought about this feature myself, to quickly reconnect, but wasn't sure about how to implement. I think reusing the hangup shortcut could work well at least to try out what it would feel like...

**Comment by ericbieller** [comment]
Agree, could be a useful feature. Curious though, if you left a group call, would you expect this key combo to attempt to reconnect with all participants? Could be a tad confusing in some scenarios.

**Comment by RalphMickelson** [comment]
Agree with the group concern. Possibly only allow reconnect if previous session was 1-on-1. All of times I have wished for a reconnect hot key have been 1-on-1s.

**Comment by tommoor** [comment]
Just for one to one is fine with me, definitely a power user feature :)

**Comment by tommoor** [comment]
I had an idea similar to this I wanted to run past you ... how about assignable, global shortcuts for individual users? This would provide very similar functionality but with even more power... :information_desk_person:

**Comment by RalphMickelson** [comment]
Excellent. That would definitely provide more power and customizability.
That would also address the never ending problem of hotkeys conflicting
with favorite app X.

**Comment by tommoor** [comment]
We just added the ability to re-call the last person in the latest release, 0.6.2, you can use the 'answer call' shortcut to recall too :smile:
