### ISSUE TITLE
High Battery Usage on MacBook Air

### ISSUE THREAD

**Issue by katiemccann** [speak/issues#65]
Ever since the last update to Speak, it's been using up a ton of battery on my MacBook Air (13", early-2015, 8GB RAM, 2.2GHz processor, running Yosemite).  It's to the point where my battery life is noticeably decreased, and Speak.app shows up under "Apps using significant energy" in the battery dropdown in the nav bar.

The weird thing is that I'm barely using Speak (have only gotten 1 of my team members using it- and we maybe chat on it for 5 min a day). I'd rather leave it running in the background (having to launch it  before talking takes away from the ease of use, obviously) but due to this battery issue have to keep closing it.

Let me know if there's any info I can send you that would help track this down.

**Comment by CyborgMaster** [comment]
I have a similar situation on my machine.  I see several processes each which constantly use CPU time (even when not in a call), from Speak.  

* Electron Helper - 5% CPU
* Speak - 2% CPU
* coreadiod - Usually runs at about 2.2%, but Speak bumps it to 3.7%, so about 1.5% CPU

Activity Monitor from when Speak is running:
![screen shot 2015-05-28 at 3 28 10 pm](https://cloud.githubusercontent.com/assets/1882579/7871768/3fecce38-054f-11e5-983f-876759c3c3b8.png)

Total, when Speak is idling, it uses about 8.5% CPU.  This is on a high-end MacBook Pro (Retina, 15-inch, Early 2013), with a 2.7 GHz Intel Core i7 (Quad-core), so I would imagine that for weaker machines, the CPU usage would be higher.

**Comment by tommoor** [comment]
Katie - that sucks definitely not how we're seeing it behave typically. Could you confirm that you are on version 0.3.2 and also how much CPU usage you are seeing - it could be that there is a bug where resources are left uncleared up...

Another bit of info that would be useful - if you go to preferences, scroll to the bottom and turn on debugging. Then click on the tray icon and open "Connection Details" and shoot us a screenshot of the top of that panel :smile: 

Thanks!

**Comment by katiemccann** [comment]
Oh yeah I had seen a few of those Electron Helper processes too (some of which are "not responding") - didn't realize they were from Speak.

**Comment by katiemccann** [comment]
OK here's the result of the Connection Details:
Peer Connection	
hadLocalRelayCandidate	false
hadLocalStunCandidate	false
hadRemoteRelayCandidate	false
hadRemoteStunCandidate	false
iceConnectionState	completed
receiveBandWidth	0kb/s
reconnectAttempts	1
reconnects	2
sendBandwidth	0kb/s
signalingReconnects	1
signalingState	stable

ssrc_3903427080_send	
audioInputLevel	0
bytesSent	0
googCodecName	opus
googEchoCancellationEchoDelayMedian	-1
googEchoCancellationEchoDelayStdDev	-1
googEchoCancellationQualityMin	-1
googEchoCancellationReturnLoss	-100
googEchoCancellationReturnLossEnhancement	-100
googJitterReceived	-1
googRtt	-1
googTrackId	4d4fdec0-4214-4d0e-95a1-92cbf1d984b8
googTypingNoiseState	false
id	ssrc_3903427080_send
packetsLost	-1
packetsSent	0
ssrc	3903427080
timestamp	
transportId	Channel-audio-1
type	ssrc

Conn-audio-1-0	
bytesReceived	1366
bytesSent	151060
googActiveConnection

**Comment by tommoor** [comment]
@katiemccann thanks! @CyborgMaster this sounds a couple of percentage points above typical but not crazy high - we're currently keeping an encrypted realtime connection open to our server and this takes a little cpu at all times. 

The plan is definitely to make this more clever and efficient as we move forward however - particularly when you're on battery power.

**Comment by CyborgMaster** [comment]
@tommoor that makes a lot of sense, and might be necessary to get the instant on audio (which I'm totally willing to give up the CPU time for).  Good luck with making it more clever in the future.

**Comment by sdhull** [comment]
Speak & Electron helper were both just pegging my CPU just now. Normally they're at about 2-8%, but just now they were both >100% and refusing to go back down.

Of course after restarting the app, it seems to have calmed back down. Maybe there's some issue resuming from sleep?

**Comment by tommoor** [comment]
Merging this one in with #95 as they are the same issue, we're very actively working on driving down cpu and improving performance with every update.
