### ISSUE TITLE
Auto-hiding speak creates an unclickable area on the screen.

### ISSUE THREAD

**Issue by brianeng87** [speak/issues#68]
Hi,

After auto-hiding Speak, it created an un-clickable area under it. I couldn't click on anything in that area that Speak would've been if it was shown.

**Comment by tommoor** [comment]
Hey @brianeng87 - could you confirm that you're using the latest version 0.3.4? thanks :smile:

**Comment by brianeng87** [comment]
I had to quit Speak and relaunch it to trigger the update dialog. But now
that it's updated, it's working fine! Thanks Tom! :D

**Comment by tommoor** [comment]
Yay, glad we could help!
