### ISSUE TITLE
Select camera source

### ISSUE THREAD

**Issue by joshkennedy** [speak/issues#71]
When using multiple displays, there's no way to select which camera Speak uses on a video call.

**Comment by willbarrett** [comment]
Hey Josh - thanks for the report! We're actually working on this right now, and hope to have something soon!

**Comment by joshkennedy** [comment]
Fantastic! Great work thus far - video and screen-sharing is huge.

**Comment by tommoor** [comment]
We've added this functionality in todays release, thanks! http://speak.io/changelog/#0.4.1

**Comment by joshkennedy** [comment]
:tada: awesome, thanks guys!
