### ISSUE TITLE
Zalgo effect in screen sharing mode

### ISSUE THREAD

**Issue by antonshulgin** [speak/issues#73]
Hi there.

Just installed 0.4.0 (12), called a friend (screen sharing mode), went fullscreen, and everything was going fine for a minute. Then, subtly, things started growing weirder and weirder, until the whole screen turned into a huge creepy mess.

![bildschirmfoto 2015-06-10 um 17 10 30](https://cloud.githubusercontent.com/assets/1933927/8086172/a83270e0-0f9c-11e5-87d1-a275f46073df.png)
![bildschirmfoto 2015-06-10 um 17 10 36](https://cloud.githubusercontent.com/assets/1933927/8086173/a8354e46-0f9c-11e5-8ed3-0f3e327298bf.png)
![pasted_image_at_2015_06_10_17_10](https://cloud.githubusercontent.com/assets/1933927/8086176/a8559476-0f9c-11e5-9780-7cbbde380030.png)
![pasted_image_at_2015_06_10_17_11](https://cloud.githubusercontent.com/assets/1933927/8086174/a84e2af6-0f9c-11e5-96a2-fc1c2e05d5a2.png)
![pasted_image_at_2015_06_10_17_13](https://cloud.githubusercontent.com/assets/1933927/8086175/a8513ab6-0f9c-11e5-8c99-dd292f7fa69b.png)

Not sure if I can provide any more details, here is an excerpt from my system info though:

**Hardware overview**
```
  Model Name:	MacBook Air
  Model Identifier:	MacBookAir5,1
  Processor Name:	Intel Core i5
  Processor Speed:	1.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	4 GB
  Boot ROM Version:	MBA51.00EF.B02
  SMC Version (system):	2.4f19
```

**Camera**
```
  FaceTime HD-Kamera (integriert):
  Model ID:	UVC Camera VendorID_1452 ProductID_34064
  Unique ID:	0x1a11000005ac8510
```

**Graphics/Displays**
```
  Intel HD Graphics 4000:

  Chipset Model:	Intel HD Graphics 4000
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1024 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x0166
  Revision ID:	0x0009
  Displays:

  Color LCD:
  Display Type:	LCD
  Resolution:	1366 x 768
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Built-In:	Yes
```

Hope it helps. C͏h̖̣͖̩̱e̴e͘r͟s.

**Comment by awsmsrc** [comment]
Hi @antonshulgin thanks for the thorough bug report. 

I know exactly what this is.

Its video feedback. 

You can avoid this by not selecting your own screen when in fullscreen mode.
or not going full screen when sharing your screen.

We'll definitely get a fix to prevent this from happening though!

**Comment by tommoor** [comment]
Hey @antonshulgin great and freaky report - reproduced:

![screen shot 2015-06-10 at 9 17 59 am](https://cloud.githubusercontent.com/assets/380914/8087781/b73152aa-0f51-11e5-8eb3-d24e2919ebdd.png)

We'll probably prevent this in the future by not letting you select your own screen in fullscreen!
