### ISSUE TITLE
Can't choose which screen to share

### ISSUE THREAD

**Issue by onetwothreebutter** [speak/issues#74]
Hi, love the new features! However, when I try to share my screen, I see all of my 3 screens with no way to choose the one I want to share. My coworkers are not having this issue, in their case, their main screen is automatically shared. I'm on a MacBook Pro (15-inch, Mid 2012) running 10.10.3.

![screen-shot-2015-06-11-at-9 24 25-am](https://cloud.githubusercontent.com/assets/3291622/8109984/5d5d9d14-101f-11e5-84b7-e9fd9caaec0a.png)

**Comment by onetwothreebutter** [comment]
Ah, I see this was already reported.

**Comment by tommoor** [comment]
@onetwothreebutter thanks for the report, it was indeed! Just adding a link here so we can count this as another vote towards getting this featured added.

https://github.com/speak/issues/issues/72
