### ISSUE TITLE
Signing in to Slack via Google causes strange behavior

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#76]
Video here: http://quick.as/og2vh6nnx

Basically, there's a minor redirect loop, then it fails.

**Comment by tommoor** [comment]
@awsmsrc this is almost definitely it trying to redirect to a location that we haven't whitelisted

**Comment by awsmsrc** [comment]
@tommoor i can fix this pretty easily but will need a google sso account to use with slack

**Comment by willbarrett** [comment]
@tommoor I think the only thing required here is to enable Google auth from the Slack admin section.

**Comment by awsmsrc** [comment]
i think this was related to: https://github.com/speak/bulldog/issues/178

gonna close and we can reopen or open a new issue with specific repro steps
