### ISSUE TITLE
Change Team Doesn't Work

### ISSUE THREAD

**Issue by julesbravo** [speak/issues#78]
Had someone send me an invite with a new team code. I tried using it and it just says Accepting but doesn't actually switch teams.

**Comment by tommoor** [comment]
Hey @julesbravo sorry for the delay in reply here, missed this issue! Are you able to try the code again?

**Comment by batilc1** [comment]
Why does change team require an invite code? I cant change my team because I am already a member?

**Comment by awsmsrc** [comment]
Hi @batilc1 changing team requires an invite code so you cant just get in to any other users account.

I will be looking into this today

**Comment by bdo** [comment]
I can confirm that the change team functionality does not work properly ... even with an invite code.

**Comment by tommoor** [comment]
Thanks both, we've found the issue and are working on a fix right now!

**Comment by awsmsrc** [comment]
Hey All,

This should work now, there was an issue in the back end so no need to update your installed clients

let me know if this is not the case :)
