### ISSUE TITLE
Users appear with blank avatars and name "undefined undefined"

### ISSUE THREAD

**Issue by jcox92** [speak/issues#79]
![image](https://cloud.githubusercontent.com/assets/844493/8114929/98e2c3f0-103d-11e5-95b0-dec755279200.png)

It goes away if I quit and re-open speak. I'm wondering if it is people who sign up on my team after I'm already logged in. Lots of people from our team are all signing up right now.

**Comment by tommoor** [comment]
Thanks Josh, we have a fix for this in the next release - we plan on pushing it out in the next 24hours :smile: 

https://github.com/speak/app/pull/1090

**Comment by jcox92** [comment]
@tommoor for a second you had me thinking your app repo was OSS and you got me super excited. Then I realized that link is private.

Looking forward to the update! Glad you and your team are so responsive!

**Comment by tommoor** [comment]
All fixed up in todays release, thanks! http://speak.io/changelog/#0.4.1
