### ISSUE TITLE
Team mates in dock

### ISSUE THREAD

**Issue by tosh** [speak/issues#8]
I've invited a bunch of team mates and was wondering what makes them appear in the dock.
Do they have to be online? Do they have to complete the sign up process? I only see myself :)

When I go to preferences it looks like this:
![2015-04-24 at 14 01](https://cloud.githubusercontent.com/assets/14825/7328432/7b78d166-ea8a-11e4-934b-59cf9a7481f8.jpg)

My dock:
![2015-04-24 at 14 02](https://cloud.githubusercontent.com/assets/14825/7328444/89f38826-ea8a-11e4-9e44-e67f648d1092.jpg)

I'm on speak `0.2.2`

**Comment by tommoor** [comment]
Hey @tosh ! Your team mates have to be online to appear in the dock right now, do you think we should show offline folks?

We should also put each persons online status in the team listing in preferences too, this might make it more obvious?

**Comment by tosh** [comment]
Thanks for the swift reply.

Random thoughts:

* show me all people even if they are not online (+ show me a 'last seen' indicator) [context & reassuring even especially for crazy time zone differences, in our case that is SFO <=> LDN & VIE (GMT/GMT+1)  <=> Sydney]
* sounds good @ replicating the information also in team listing
* in my screenshot from above it wasn't clear to me what it means for team members to be above vs below 'Team'
* give me another status 'online but not available for instant audio' [show me if someone requests instant audio]

love the ergonomics, very polished!

**Comment by tommoor** [comment]
Okay, killer feedback - I think we can make some improvements here immediately:

- We'll look at adding an option to show offline folks in the dock, it seems like this is just going to be a matter of team size for if people need this or not.
- Replicate offline/online status in the team listing
- Move the invites heading below the invite field
- Add an option to 'nudge' / 'resend' an invite that hasn't been accepted
- Add option for online but not in instant audio ( this is already coming in the next release 0.2.3 on Mon!)

**Comment by tommoor** [comment]
Hey @tosh, just pushed out version 0.2.5 which includes all the fixes above apart from resending invites which I'll separate into its own issue :smile:

**Comment by tosh** [comment]
\o/
