### ISSUE TITLE
Too many team members causes a loss of your own profile picture and therefore settings

### ISSUE THREAD

**Issue by mathewschrader** [speak/issues#80]
I enabled the option to show offline team members. Now 15 bubbles are shown (15in MBPr), but I can't get to mine to get back into the settings to turn that option off. Regardless of the status of the option, if there are more than 15 members online at the same time, it seems like this would still be an issue.

**Comment by tommoor** [comment]
@mathewschrader thanks! You can get back to the option by clicking on the speak icon in the menu bar > preferences > untick show offline users

We're working on a better solution for how this should work with larger teams. If you have any thoughts then we're all ears :)

**Comment by mathewschrader** [comment]
Hey look! There's a Speak icon on the menu bar... Sorry I missed that

**Comment by mathewschrader** [comment]
RE: larger teams. I'm assuming you're just grouping us by our @hudl email addresses. With an org as large as we are now, there's now way I'll want/need everyone (250+) up at any given time. But I will want just my team (~14) up at all times, both online and offline. If there were a way to pin just the users you want, but still access the whole organization with a keystroke, that'd be sweet. Command-K in Slack comes to mind first.

**Comment by tommoor** [comment]
Thanks for the thoughts! Going to combine this one with #46 as the problem is the same :)
