### ISSUE TITLE
Speed up bouncing when being called

### ISSUE THREAD

**Issue by tommoor** [speak/issues#81]
Thinking of doubling the bounce speed. This came in via our user survey and got to say I agree:

> "Would love to be able to have the caller constantly bounce—not just on the ringing sound—to easily see who is calling immediately without having to _wait_ for the next ring/bounce"

**Comment by ericbieller** [comment]
Sounds good, so it would be something like ring/bounce, bounce, ring/bounce, bounce?

**Comment by tommoor** [comment]
exactamundo
