### ISSUE TITLE
Can not click avator when Dock is in the left side of the screen.

### ISSUE THREAD

**Issue by hairihan** [speak/issues#83]
Can not click avator when Dock is in the left side of the screen.
[Mac OS X]

**Comment by tommoor** [comment]
Hey @hairihan sorry for any trouble you're having here. Do you have some more details as to what the problem is here? Perhaps some steps we could use to try and create the problem?

Thanks!

**Comment by tommoor** [comment]
Hey @hairihan please reopen if you have more details and try out the latest release - 0.4.1
