### ISSUE TITLE
"Start Speak when your Mac boots up" is not respected

### ISSUE THREAD

**Issue by max** [speak/issues#84]
Version: 0.4.0
OS: OS X 10.10.3

Summary: "Start Speak when your Mac boots up" is not respected and is annoying (specially because the app is not easy on resources).

Steps to reproduce:

1. Disable "Start Speak when your Mac boots up"
2. Restart Mac (uncheck "Reopen windows when logging back in")
3. Speak opens

Expected outcome:

Speak respects the "Start Speak when your Mac boots up" setting and does not open on login when setting is false.

**Comment by tommoor** [comment]
Hey @max - sorry about that. Could you check in your login items to see if there are perhaps two different entries for Speak? It should look like this:

![image](https://cloud.githubusercontent.com/assets/380914/8150826/5171430c-12ae-11e5-844c-50d35fb20bfb.png)

Or in the case where this option is unticked obviously Speak shouldn't show there at all...

**Comment by max** [comment]
Option is unselected and I see:

![image](https://cloud.githubusercontent.com/assets/111631/8150881/779b83c4-12b0-11e5-88fa-a0db3f119e8d.png)

![image](https://cloud.githubusercontent.com/assets/111631/8150879/6c240872-12b0-11e5-9288-c6fecf74b39a.png)

**Comment by tommoor** [comment]
Thanks @max I see the error and we'll have a fix in the next release (on Monday). In the meantime you can manually remove Speak from the login items in that window and it won't re-add itself :smile:
