### ISSUE TITLE
Speak as phone app

### ISSUE THREAD

**Issue by iannowosad** [speak/issues#85]
Within our team, 50% are always working remote/in the field. It would be great to see an iPhone app for this so we could use it immediately across the company.

**Comment by tommoor** [comment]
Hey @iannowosad - one i've idea we've had is to have Speak fallback to a phone number when your team mate isn't logged in so you can click on them as normal in Speak but it will reach their phone, thoughts?

**Comment by tommoor** [comment]
Closing this for now, whilst we'd like to support phones in the future and appreciate the request just keeping these issues for the desktop only right now :smile_cat:
