### ISSUE TITLE
Unable to change slack team and Revoked API Token is not respected

### ISSUE THREAD

**Issue by batilc1** [speak/issues#86]
I successfully sign out of my slack account in speak. Then I try signing in using a different team/id in slack. When signing in completes, speak shows the contacts from my previous team (which I had used when I initially setup speak.io)

I went on to remove access tokens from api.slack.com for speak.io. Even then, it consistently logs me in with my previous contacts. When I do sign out/sign in in speak io, it correctly shows that I have logged in with the new team ID. But contacts are still old and I am able to contact people from the old team. It is distrubing that it still works even though I removed all access tokens from the slack API.

**Comment by tommoor** [comment]
Hey @batilc1 - sorry for the confusion here. Do you know if you use the same email address for both accounts? It could be this that is linking them across

**Comment by batilc1** [comment]
Yes exactly, I am using same mail address for my multiple Slack teams. I signed up to speak using one of the teams, now that team is inactive and I tried changing speak to another team, which created the problem.

I managed to switch current team using the following way: My friend in the new team send me an invitation, I got a mail with the invitation code, and using that code I could use `change team` button. But now I am stuck in this team :) Note that, this was the first sign-up of that guy. So, if he had also been a previous user of speak (with another slack team),  this method would not work.

Not signing out does not work and i am always linked to the current team even though I revoke tokens

**Comment by tommoor** [comment]
Hey @batilc1 - right now you can only have one Speak account associated with an email address, Slack signin does not change this. You can also only be signed into one Speak account at a time - when you accepted an invite into another org you simply moved your account... we're working on making this messaging much clearer!

**Comment by batilc1** [comment]
OK, thanks for the notice. I thought, once signed in, i could switch teams as easily as we do in slack. It'd be nice if we had an option do dissociate our slack account from the speak account so that re-registration with a different team is made possible (even though with some hassle)

**Comment by tommoor** [comment]
@batilc1 totally agree, we'll need to add a 'connected accounts' type of page to let you do this!
