### ISSUE TITLE
Show dock doesn't work

### ISSUE THREAD

**Issue by WartClaes** [speak/issues#87]
When I use Speak (0.4.1), I can't activate the dock on the side of the screen. It just keeps popping up random, but I can't activate it myself.

The moment I disconnect my second screen and only work on my laptop, the feature works fine for a while. If I reconnect my second screen works again, but then it just stops.

**Comment by tommoor** [comment]
Hey @WartClaes sorry about that - do you have any more details on your screen setup?

If you have a desktop screenshot with the layout that would be perfect

**Comment by WartClaes** [comment]
Maybe it has more to do with the unstable internet at my work location.

I think I can close this issue, but maybe make another one for a animated 'connecting' icon. Because I didn't see that I lost my connection and that it was trying to reconnect :-) 

I'm sorry for the misunderstanding...
