### ISSUE TITLE
Animated icon when connecting

### ISSUE THREAD

**Issue by WartClaes** [speak/issues#88]
Is it possible to create an animating icon when the service is connecting. At the moment you have no visual clue wether or not you have an issue.

**Comment by tommoor** [comment]
Hey @WartClaes that's a good idea. We actually fade the menu icon to a half transparent state when you're offline, this is similar to Dropbox and some other apps... we should probably augment the icon a bit at least

**Comment by tommoor** [comment]
We're no longer displaying a menu icon in favor of a more traditional floating window during these times that will display a connecting bar or warning message if there are internet issues.
