### ISSUE TITLE
Make current calls more obvious

### ISSUE THREAD

**Issue by lsinger** [speak/issues#89]
It's a nice touch that you can glance from the Dock who's currently in a call. I'd prefer to have that a bit more obvious though, e.g. by using a different border color.

**Comment by tommoor** [comment]
Hey @lsinger ! Definitely an interesting one, we want to make sure that the calls are obvious if you take a look but not be distracting otherwise, a fine balance...

**Comment by lsinger** [comment]
Yup, totally understand! Right now the pulsing indeed *is* a bit distracting, while the difference is hard to see in between the pulses. But maybe that's just me. :)

**Comment by tommoor** [comment]
@lsinger we're now displaying a floating widget in the top right of the desktop when a call is taking place. We think it's the right balance of out of the way vs obviousness.

Give it a try and tell us what you think
