### ISSUE TITLE
Speak uses too much CPU during video calls

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#90]
We're still trying to figure out exactly what's causing this behavior. Any clues would be helpful!

**Comment by jonlogan** [comment]
I'm running 2015 MacBook Air, Core i7, 8GB RAM, MacOS Yosemite.  Speak devoured upwards of 110% of my CPU (how is > 100% even possible!?  arithmetic fail, Apple?!).

Performance didn't return to normal levels until I completely quit the Speak app.

![screen shot 2015-06-17 at 1 17 08 pm](https://cloud.githubusercontent.com/assets/12702821/8241677/9dd6697a-15bf-11e5-8ae8-700fc6f3bb4c.png)

**Comment by tommoor** [comment]
Hey @jonlogan is this after an audio or a video call? 100% means one core, so if your i7 has 2 cores then it is capable of going to 200% :smile:

**Comment by jonlogan** [comment]
Sorry, its a video call, and with multiple parties.  Thanks for explaining the math too.  

Unfortunately, when its running at that capacity, my entire machine starts stuttering and becomes very difficult to use.

**Comment by tommoor** [comment]
@jonlogan understood how this would make the machine unresponsive. Just to be really clear:

- Is this during a video call, or after?
- If during, how many parties are in the call, how many on video?

Thanks!

**Comment by jonlogan** [comment]
Most notably during the video call.  We had a large call with about 6-8 attendees.  Performance improved after the call ended, but my machine was still stuttering until I fully quit your app and also restarted Chrome.

**Comment by tommoor** [comment]
@jonlogan thanks - this level of CPU usage (50% of total) is expected at the moment during a multiparty video call, you'd find similar in Hangouts in my experience...**However** we're not happy with this of course and are investigating using a hardware accelerated codec like H.264 in future versions of the app.
