### ISSUE TITLE
Profile fields are empty after signup

### ISSUE THREAD

**Issue by callovarne** [speak/issues#91]
### Steps

1. Install
2. Complete signup
3. Navigate to Speak > Preferences > Profile

### Expected behavior

Profile fields have values from signup.

### Actual behavior

Profile fields are empty.

#### Notes

Restarting the app syncs everything up.

**Comment by willbarrett** [comment]
Hey @callovarne - thanks! Great bug report! We'll get it fixed up.

**Comment by tommoor** [comment]
Thanks @callovarne - I can confirm we have fixed this and it will be in the next release. Appreciate the report! :smile:
