### ISSUE TITLE
Windows spawned from OS X menu bar lost behind other windows when focus changes

### ISSUE THREAD

**Issue by callovarne** [speak/issues#92]
### Steps

1. From the OS X menu bar, Navigate to _Speak > Preferences_
1. Become distracted; click on another app's window
1. Again, nav to _Speak > Preferences_

### Expected behavior

Preferences window gains focus.

### Actual behavior

Preferences window appears "lost", is really hiding.

#### Notes

OS X 10.10.3

**Comment by tommoor** [comment]
Hey Patrick,

Great stuff - it appears we must have broken this recently :cry: we'll get it fixed up for the next release!
