### ISSUE TITLE
App hangs on connecting signing in with Slack

### ISSUE THREAD

**Issue by fvadicamo** [speak/issues#94]
After my first successful sign in with Slack now I cannot sign in anymore: 
- clicked on Sign in with Slack 
- picked my existing team 
- authorized Speak as third-party App
- App hangs on connecting...

**Comment by tommoor** [comment]
@fvadicamo our engineers tell me that this was a temporary error on our backend, could you give it another try perhaps? Thanks so much!

**Comment by fvadicamo** [comment]
Unfortunately the issue is still here! I was able to Sign in again (just one time) but after that no dock was shown and status is "Connecting..." :(
![screenshot 2015-06-23 14 02 17](https://cloud.githubusercontent.com/assets/1905363/8305636/53ae39c2-19b1-11e5-90c5-4f257628252b.png)

**Comment by tommoor** [comment]
@fvadicamo any network limitations / firewalls we should be aware of? Also could you let us know how far across the connecting bar gets... half way or three quarters?

Thanks :) /cc @awsmsrc

**Comment by fvadicamo** [comment]
Today the bar goes over three quarters and then the dialog disappears (yesterday was half and the dialog has remained visible). However today I'm connected from a different office so actually there could be some network limitations.
I will try tomorrow and I'll let you know. 
Thanks for the support!

**Comment by fvadicamo** [comment]
I just came back to my office and all works fine now, thank you very much!

**Comment by willbarrett** [comment]
Awesome! Thanks for the update!
