### ISSUE TITLE
Speak occasionally uses too much CPU while idle

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#95]
When not in a call, Speak uses far too much CPU. Seen so far on:

MacBook Pro (15-inch, Mid 2010) OS X Yosemite 10.10.3 (14D136)

**Comment by tommoor** [comment]
It doesn't typically use *too much* - if it is running hot then there is an as yet unidentified issue

**Comment by willbarrett** [comment]
Yes - apologies - title updated to reflect reality.

**Comment by awartani** [comment]
Please let me know if I can provide any more details, It happened on my machine.

**Comment by sdhull** [comment]
Happening on my machine right now! You want me to dtrace it or something? I'm not really familiar with dtrace but ya know, "speak" quickly because I'm going to kill it in 10 mins or so

**Comment by tommoor** [comment]
@sdhull can you jump on a 5min screenshare? I'll be here for 5mins:

https://g2m.me/triple-sun-violet

**Comment by tommoor** [comment]
Just been on a screenshare with @sdhull - a couple of screenshots from the console during this time:

![screen shot 2015-07-02 at 10 47 55 am](https://cloud.githubusercontent.com/assets/380914/8483847/80f4cda8-20a8-11e5-9778-e6b188698691.png)
![screen shot 2015-07-02 at 10 46 10 am](https://cloud.githubusercontent.com/assets/380914/8483846/80f4655c-20a8-11e5-8607-fe8c44b6bac0.png)

Anomaly in user.back events. The app also said it was 'conneting' in the menu however there was no evidence of it retrying a connection

**Comment by sdhull** [comment]
@tommoor And after I closed gotomeeting, speak & electronhelper climbed back to 120-130% CPU usage.

**Comment by sdhull** [comment]
last thing -- when I chose "Quit", I got "Speak is not responding" with options to keep waiting or close, like you would on a web page with an infinite js loop...

**Comment by tommoor** [comment]
We're no longer seeing this issue!
