### ISSUE TITLE
Incorrect times for some users

### ISSUE THREAD

**Issue by benkuhn** [speak/issues#97]
Thanks for making Speak!

My team has users in both Pacific and Eastern time. The Eastern people are showing the correct timezone in my dock, but the Pacific users aren't; they're showing what appears to be GMT instead. (I'm in Pacific time.)

**Comment by tommoor** [comment]
Hey @benkuhn it looks like these might be the users that have yet to signin to speak themselves... the timezone gets set when they first login. Good spot!

**Comment by benkuhn** [comment]
Hmm--that seems unlikely, since it includes my own account, and the account
of another user who's online right now. (I assume there's no way they got
online without signing in?)

**Comment by awsmsrc** [comment]
so @benkuhn to be clear, the time shown is wrong for your account?

What timezone are you currently in?

**Comment by benkuhn** [comment]
That's correct, and I'm in PDT.

That said, the timezone is correct now for myself and the other PDT person.
(This might be related to the fact that I had to restart Speak this morning
when it crashed.) So maybe restarting is a workaround?

**Comment by tommoor** [comment]
@benkuhn definitely a clue, I'll try and reproduce it with a fresh signup!

**Comment by tommoor** [comment]
Thanks for reporting! This was infact an issue that could be fixed on our backend and has now been deployed
