### ISSUE TITLE
App gets stuck "connecting"

### ISSUE THREAD

**Issue by ericbieller** [speak/issues#98]
Tough one to repro, but happens from time to time when resuming from sleep / opening my lid. Few other users have reported similar issues.

> I think the issue is that it always seems to say "Connecting" for me and doesn't fully load after I start up my computer any longer...

In this instance, the app *did* end up connecting finally after about 10 minutes of trying. Whats more I was stuck in idle when it came back.

Dump here https://www.dropbox.com/s/al3ja96la5m95q8/Eric%20Console%20Dump.log?dl=1

**Comment by tommoor** [comment]
It appears to be timing and retrying the webrtc connection:

![image](https://cloud.githubusercontent.com/assets/380914/8343443/3e642d18-1a8a-11e5-8aac-111de43cfa79.png)

We have a fixed connection timeout of 5 seconds, if the client hasn't had an answer back from the server in that time it resets. Is this just a really slow connection? We might need to dynamically increase that timeout, although 5s is already quite generous.

**Comment by tommoor** [comment]
@awsmsrc although we fixed one thing with the offer yesterday, I think this is the bigger (and looks like backend) issue..

**Comment by ericbieller** [comment]
Here's my [Dump](https://www.dropbox.com/s/nlg7ruzxo1bse97/Eric%20Console%20Dump%206-25.log?dl=0)
